### ISSUE TITLE
Не получается установить модуль

### ISSUE THREAD

**Issue by tarnazar** [yandex-money/yandex-money-cms-opencart2#1]
Пробую установить Яндекс.Пак в меню feed выводит просто белый экран. В ошибки ничего не уходит. Захожу заново, пишет, что уже установлено. Но я так понимаю, что не применяется model. Дальше ругань на отсутствующие таблицы в базе. Подскажете куда копать?

**Comment by ded100let** [comment]
Пробуйте. Модуль обновлён

**Comment by ded100let** [comment]
если что пишите в 2343319@gmail.com

**Comment by polozov** [comment]
tarnazar, здравствуйте!
Описанная вами проблема решена? issue можно закрывать?

**Comment by tarnazar** [comment]
Прошу прощения, что не ответил. Нет не решена. Но пока не могу указать детали и ошибки. Постараюсь в течение недели проверить более точно, и в случае чего отпишу. Спасибо.

**Comment by ded100let** [comment]
Включите отображение ошибок. Модуль проверен на всех ОС 2
