### ISSUE TITLE
Смена статуса заказа

### ISSUE THREAD

**Issue by Keksoidik** [yandex-money/yandex-money-cms-opencart2#100]
При смене статуса заказа на любой другойв админке сайта, не меняется статус в маркете. В чем проблема ?

**Comment by Keksoidik** [comment]
И еще вопрос Callback URL для приложения OAuth меняется каждый раз когда заходим в админку, так должно быть ?

**Comment by xxBRATxx** [comment]
Поддерживаю оба вопроса от @Keksoidik 
Еще вопрос: - Использую модуль Почты России (автоматический расчет стоимости доставки в тот или иной регион) - как это передать в маркет при выборе метода доставки?

**Comment by ikarmanov** [comment]
Добрый день.

> При смене статуса заказа на любой другойв админке сайта, не меняется статус в маркете. В чем проблема ?

Рекомендую направить Ваш вопрос на cms@yamoney.ru. Коллеги помогут разобраться.

> И еще вопрос Callback URL для приложения OAuth меняется каждый раз когда заходим в админку, так должно быть ?

Да, т.к. этот адрес используется для получения токена. Подразумевается, что он будет получен во время одной сессии администратора магазина.

> Использую модуль Почты России (автоматический расчет стоимости доставки в тот или иной регион) - как это передать в маркет при выборе метода доставки?

Мы думаем над этим вопросом. Некоторое решение есть в [модуле 1.6.1.2](https://github.com/yandex-money/yandex-money-cms-opencart2/releases/tag/1.6.1.2) для Opencart 2.0.x-2.2.x
