### ISSUE TITLE
Yandex CPA и SEO PRO. Давайте разберемся!

### ISSUE THREAD

**Issue by tidzh** [yandex-money/yandex-money-cms-opencart2#101]
Есть какие нибудь подвижки в "дружбе" между Yandex CPA и SEO PRO .  Страница /yandexbuy отдает 404 ошибку. Кроме того, побывал отключать SEO PRO, но результат все тот же - 404 ошибка!

Хотелось бы посмотреть демо успешной работы, что браузер должен выдавать при успехе.

**Comment by xxBRATxx** [comment]
попробуй в .htaccess дописать.

RewriteBase /
RewriteRule ^yandexbuy/([^?]*)$ index.php?route=yandexbuy/$1 [L,QSA]

если заработает, сообщи, самому интересно

**Comment by tidzh** [comment]
@xxBRATxx 

Это правило и так было добавлено в .htaccess. Окей, хорошо. Допустим, что правило не работает, допустим, что конфликт с SEO PRO, но разве не должен модуль работать по ссылке /index.php?route=yandexbuy?

В логе яндекса ошибка CANT_GET_RESPONSE

Параметры URL: auth-token=BE000001C757A4A0
Детали ошибки = 301 Moved Permanently

**Comment by xxBRATxx** [comment]
@tidzh я проверил с отключенным seo pro, работает но не стабильно, периодически не получает тот или иной параметр. я думаю, что тут само соединение api глючит, так поучение данных идет не на прямую

**Comment by tidzh** [comment]
@xxBRATxx  можешь приложить скриншот страницы с "рабочим" примером?

**Comment by xxBRATxx** [comment]
@tidzh да, вот.
![api-1](https://cloud.githubusercontent.com/assets/22705233/19466438/7b4398f4-9513-11e6-82bf-d53aee80f3ac.jpg)
![api-2](https://cloud.githubusercontent.com/assets/22705233/19466441/7f7d2e12-9513-11e6-8b8a-ebaf11a20dcf.jpg)
![api-3](https://cloud.githubusercontent.com/assets/22705233/19466443/8200c414-9513-11e6-8864-7a211d4155c0.jpg)
![api-4](https://cloud.githubusercontent.com/assets/22705233/19466445/8431ab5e-9513-11e6-90da-d17a0e0e3eb5.jpg)

**Comment by tidzh** [comment]
@xxBRATxx скриншот страницы /yandexbuy/ Плиз ))

**Comment by xxBRATxx** [comment]
@tidzh уже не могу, снес модуль еще на прошлой неделе

**Comment by tidzh** [comment]
@xxBRATxx что-то типо белого экрана с надписью "Все хорошо"?

**Comment by xxBRATxx** [comment]
@tidzh было, но уже нет модуля

**Comment by ikarmanov** [comment]
Добрый день.

Проблема при работе с SEO PRO вызвана отсутствием возможности добавить исключение для некоторых запросов (от Яндекс.Маркета к модулю).

Яндекс.Маркет отправляет запросы на URL domain/yandexbuy/cart и передает дополнительный параметр auth-token=ХХХ, т.е. domain/yandexbuy/cart?auth-token=ХХХ. Без этого правила мы получили бы запрос domain/index.php?route=yandexbuy/cart?auth-token=ХХХ

**Comment by tidzh** [comment]
Ну так что в итоге? Ведь у 99% магазинов установлен  SEO PRO.

**Comment by lennt92** [comment]
Может спустя год появилось какое-нибудь решение по данной проблеме ?)
