### ISSUE TITLE
OpenCart 2.3 Y.Market

### ISSUE THREAD

**Issue by Vladimir32111** [yandex-money/yandex-money-cms-opencart2#104]
Должен ли работать Я.Маркет на версии 2.3 ?
Произвел установку, но не работает, настройки сохраняются, но не дает скопировать адрес XML-файла.
При открытии этого адреса в браузере - пустой экран.

**Comment by ikarmanov** [comment]
Добрый день.

Мы разделили модуль на две версии - 1.х и 2.х для совместимости с разными версиями Opencart 2.x
