### ISSUE TITLE
<offers></offers> - тут пусто

### ISSUE THREAD

**Issue by HugeTool** [yandex-money/yandex-money-cms-opencart2#105]
Заменил true на false, как советовали тут #47 
 `$products = $this->model_yamodel_yamarket->getProducts($ids_cat, false); `  - не помогло. где еще можно поискать причину?
ocStore 2.1.0.2.1 
Версия модуля 1.6.0

_кстати, если у Валюты кол-во знаков после запятой = 0, то yml не генерится, выдает ошибку._

**Comment by ikarmanov** [comment]
Добрый день.

Мы учитываем пожелания наших пользователей и в новой версии модуля для Opencart 2.0.x-2.2.x исключили появление некоторых предопределенных исключений.

**Comment by HugeTool** [comment]
Проблема была в наличии знака "&" в описании товара (например, Plug&Play), решилось заменой на &amp;
