### ISSUE TITLE
Как настроить модули?

### ISSUE THREAD

**Issue by megasvf** [yandex-money/yandex-money-cms-opencart2#106]
Установил ваш модуль к себе на Opencart 2.1, но после установки и очистки кеша модификаторов я не знаю, что делать, т.к полей для настройки в админке нет, FAQ не помогло, а в README только описание.
Что делать дальше, чтобы настроить себе Яндекс метрику? Нужно менять что-то в коде или в админке?

**Comment by megasvf** [comment]
Нашел. Оказывается все засунули в "модули-оплата", там и метрика, и маркет и касса.

**Comment by vovtil** [comment]
а у меня нигде не появляется

**Comment by ikarmanov** [comment]
Добрый день.

Для Opencart версии 2.3.x необходимо устанавливать [модуль версии 2.х](https://github.com/yandex-money/yandex-money-cms-opencart2/releases/download/2.0.1/ycms.23x.ocmod.zip). Еще необходимо убедиться, что файлы модуля версии 1.х удалены, т.к. они будут только мешать.

**Comment by kvai** [comment]
Выполнил все рекомендации, модуль также не появляется ни в каналах продвижения ни где-либо еще. Opencart 2.3

**Comment by ikarmanov** [comment]
FTP в настройках Opencart настроен корректно?
Рекомендую обратиться в поддержку модуля по адресу cms@yamoney.ru
