### ISSUE TITLE
Яндекс касса

### ISSUE THREAD

**Issue by vicgor** [yandex-money/yandex-money-cms-opencart2#11]
Не удается провести платеж с помощью Яндекс.Касса

Получаю сообщение
	
Провести платеж не удалось.

Магазин передает некорректные параметры. Пожалуйста,обратитесь в службу поддержки магазина

/**/jQuery17037612572219222784_1426137161953({"unread": 9})

**Comment by ded100let** [comment]
значит так и есть. пишите в скайп d-link570

**Comment by vicgor** [comment]
исправлено форматирование цены
