### ISSUE TITLE
Ошибка при оплате из кошелька в Яндекс.Деньгах без авторизации

### ISSUE THREAD

**Issue by neccospb** [yandex-money/yandex-money-cms-opencart2#110]
Доброго времени суток. Выявлена ошибка:
Если покупатель перед оформлением заказа не авторизовался в Яндексе, модуль Яндекс.Деньги редиректит на несуществующую страницу после оплаты.

> http://.../index.php?route=payment%2Fyamodule%2Finsidewallet&code=....
Запрашиваемая страница не найдена!
К сожалению, запрашиваемая Вами страница не найдена. Вероятно, Вы указали несуществующий адрес, страница была удалена, перемещена или сейчас она временно недоступна!

Оплата не проходит, заказ не создается.
Если перед оформлением авторизоваться в Яндексе, модуль отрабатывает как надо. Куда подскажете копать?
oc 2.1.0.2 (rs.1)

**Comment by ikarmanov** [comment]
Добрый день.

Информацию проверяем.

**Comment by ikarmanov** [comment]
Предлагаю установить модуль версии 2.1.0. Сообщите результат.
