### ISSUE TITLE
Ошибка парсинга <group_id>

### ISSUE THREAD

**Issue by wastesoul** [yandex-money/yandex-money-cms-opencart2#112]
Использую opencart 2.3.0.2
При добавлении yml в яндекс маркет после проверки выдается ошибка:
Фатальная ошибка: Ошибка парсинга XML: Error parsing XML feed: Unknown tag: XML tag "group_id"

Судя по хелпу (https://yandex.ru/support/partnermarket/offers.xml) group_id - это аттрибут тега offer.
Но у меня ваш плагин создает не аттрибут, а отдельный тег. Получается так:
<group_id>12345</group_id>
вместо 
<offer ............. group_id="12345">

**Comment by ikarmanov** [comment]
Добрый день.

Ошибка обнаружена и устранена в модуле для Opencart 2.0.x - 2.2.x. Скоро поправим и для модуля на Opencart 2.3.

**Comment by ikarmanov** [comment]
Вышла новая версия модуля, которая сразу совместима с Opencart 2.0.x-2.3.x
