### ISSUE TITLE
Ошибка в отображении блока Заказы(Orders)

### ISSUE THREAD

**Issue by lyolic** [yandex-money/yandex-money-cms-opencart2#114]
Opencart 2.3.0.2 Yadex Module: 2.0.1
Проблемы на вкладке Sales-> Orders:
1. Когда активирован модуль от яндекса, левая панель начинает наезжать на таблицу заказов.
2. Когда подключён Яндекс Кошелёк, рядом с заказом появляется зелёная "кнопка управление заказом", которая не работает и выдаёт Warningи.
![](https://cloud.githubusercontent.com/assets/18102692/18166242/aefdcac4-7052-11e6-9255-6664b6db9362.jpg)

**Comment by edichome** [comment]
Присоединяюсь к предыдущему отзыву. Проверить кассу не могу полностью потому, что нет аккаунта (только Яндекс Деньги)
В расстановке блоков допущена ошибка, на странице заказов при активации модуля 
<div class="container-fluid"> должен быть внутри <div id="content">, в результате контейнер растягивается на всю ширину экрана и перекрывается боковым меню. Кнопки тоже не на месте, "Удалить" у меня слева.
![2017-01-20 23 21 05](https://cloud.githubusercontent.com/assets/5670645/22154846/1a11d8da-df68-11e6-90e7-976ee2e8adec.JPG)
![oc-order](https://cloud.githubusercontent.com/assets/5670645/22154871/31a71b18-df68-11e6-9ef2-599311907d1d.JPG)

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо за информацию. Вы правы. Дополнительно проверим на модуле для Opencart 2.0.x-2.2.x. Скоро исправим.

**Comment by Qkoss** [comment]
Есть такая ошибка. 
Скажите, пожалуйста, когда планируете поправить? 
![default](https://cloud.githubusercontent.com/assets/26418886/23920812/2b8a466e-090d-11e7-96f3-42e338a59812.JPG)

**Comment by ikarmanov** [comment]
Выпустили новую версию модуля. Рекомендую обновить и проверить.
