### ISSUE TITLE
Opencart 2102 - окмод не цепляется

### ISSUE THREAD

**Issue by VayBoy** [yandex-money/yandex-money-cms-opencart2#116]
**43 строка мода**
<search position="replace"><![CDATA['view'          => $this->url->link('sale/order/info', 'token=' . $this->session->data['token'] . '&order_id=' . $result['order_id'] . $url, true),]]></search>

в admin/controller/sale/order.php
искомая строка выглядит так: (172)

'view'          => $this->url->link('sale/order/info', 'token=' . $this->session->data['token'] . '&order_id=' . $result['order_id'] . **$url, 'SSL')**,

**На 22 строке вы ищите**   $_['text_add'] = 'Add Order'; 
во всех языковых папках, это неправильно, в папке с русским такой строки не будет

и т.д.
ошибок куча.
просьба провести допил окмода

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо за информацию. Обязательно проверим.

**Comment by VayBoy** [comment]
мне тут лениво стало расписывать, но в общем всё с оранжевым справа - это не найденные строки, соответственно - замены/добавления не прицепились.

http://uploadme.ru/image/wh0

с кассы пока что апру не получен - страница заказа сыпет ошибками, свои подсказывают, что сначала апрув нужно получить от кассы, на данный момент мод отрублен

**Comment by ikarmanov** [comment]
Спасибо за подробности.

> начните хотя бы с порядка в языковых файлах, в папках russian - храним русскоязычные файлы, в папках с инглишем - английские

Вы правы. Скоро поправим

**Comment by ikarmanov** [comment]
Добрый день.

Изменения добавлены в новую версию модуля (2.1.0).
