### ISSUE TITLE
Opencart  2.3.0.2 Не работает метрика

### ISSUE THREAD

**Issue by bombapiter** [yandex-money/yandex-money-cms-opencart2#118]
Здравствуйте.
Установил Y.CMS от Яндекс.Кассы (2.0.1) 

Вроде бы всё настроил, в админке ошибок нет, а метрика не показывается - код метрики не установливается!
Или после настройки (Номер счётчика, ID Приложения, Пароль приложения, Токен OAuth)  еще что-то делать надо?

**Comment by ikarmanov** [comment]
Добрый день.

Модуль через API сервиса Яндекс.Метрика получает код счетчика и добавляет его в подвал сайта через файл модификатора (*.xml). Проблему можно понять через просмотр журнала модификаторов. Вы можете отправить его содержимое на адрес поддержки модуля (cms@yamoney.ru) и коллеги помогут найти причину.

**Comment by bombapiter** [comment]
Здравствуйте.
Проблема решена.
Причина:  не стандартный шаблон. Файл "catalog/view/theme/*/template/common/footer.tpl" не используется, а используется "catalog/view/theme/tmpl_name/template/footer/footer1.tpl"
Из-за этого код метрики не прописался в используемый footer1.tpl

Прописал руками.

Вот бы при установке учитывать этот момент.

**Comment by ikarmanov** [comment]
Спасибо за обратную связь. Подумаем над этим.

**Comment by daytovar** [comment]
после установки не нашел код не в стандартном, не в текущем шаблоне
куда сейчас прописывается код, так же в footer.tpl?
счетчик соответственно не работает
