### ISSUE TITLE
Разваливается дизайн страницы заказа на Opencart 2.3.0.1 с модулем для 2.3

### ISSUE THREAD

**Issue by miken912** [yandex-money/yandex-money-cms-opencart2#120]
Лишний тег в instal.xml  `</div>`
`<file path="admin/view/template/sale/order_list.tpl">
		<operation>
			<search position="replace"><![CDATA[<a href="<?php echo $add; ?>" data-toggle="tooltip" title="<?php echo $button_add; ?>" class="btn btn-primary"><i class="fa fa-plus"></i></a>]]></search>
			<add><![CDATA[<a href="<?php echo $add; ?>" data-toggle="tooltip" title="<?php echo $button_add; ?>" class="btn btn-primary"><i class="fa fa-plus"></i></a>
			        <a href="<?php echo $invoice_kassa; ?>" data-toggle="tooltip" title="<?php echo $button_invoice_kassa; ?>" class="btn btn-warning"><i class="fa fa-envelope"></i></a>**</div>**]]></add>
		</operation>`

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо за информацию. Проверим.

**Comment by ikarmanov** [comment]
Спасибо. Убрали в новой версии модуля.
