### ISSUE TITLE
ошибка в yml в новой версии модуля

### ISSUE THREAD

**Issue by sh2rman** [yandex-money/yandex-money-cms-opencart2#122]
доброго времени суток! поставил свежак
у меня валюта по умолчанию она же единственная - BYN, и пока не сменил её в строке 27 в контроллере каталога yml не генерировался. 

теперь файл выводится но с таким сообщением:
error on line 719 at column 651: xmlParseEntityRef: no name http://prntscr.com/ejz3dr
и далее весь текст без тегов и форматирования

**Comment by ikarmanov** [comment]
Добрый день.

Вышла новая версия модуля с изменениями по валюте BYN. Рекомендую обновить до актуальной версии и проверить формирование прайс-листа.

**Comment by sh2rman** [comment]
http://prntscr.com/en14ll

**Comment by sh2rman** [comment]
контроллер от старой версии 1.6 работает нормально

**Comment by sh2rman** [comment]
исправил на
`if (strlen($data[$k])>=1000) {
					$iCut = strpos($data[$k], ' ', 785);
					$iCut = ($iCut > 1000) ? strpos($data[$k], ' ', 785) : $iCut;
					$data[$k] = substr($data[$k], 0, $iCut);
				}`
так работает
