### ISSUE TITLE
Метрика. Цели.

### ISSUE THREAD

**Issue by Qkoss** [yandex-money/yandex-money-cms-opencart2#123]
В составе модуля есть настройка целей для Я.Метрике.
Сейчас модуль добавляет отслеживание нажатий кнопок купить и у меня не работает одна из кнопок, а именно быстрый заказ. 
Разработчик моего шаблона предлагает, для решения проблемы, совершить следующую замену:
cart.add = function (product_id, quantity) 
на 
cart.add = function (product_id, quantity,quick_order) 
и 
old_addCart(product_id, quantity); 
на
old_addCart(product_id, quantity,quick_order) ; 

Подскажите пожалуйста где это можно сделать и если заменить будет ли передаваться данные в Метрику? 

Заранее спасибо.

**Comment by ikarmanov** [comment]
Добрый день.

Разработчик шаблона указывает изменения для файла ycms.ocmod.xml, который после правок на вашем ПК нужно установить в Вашем магазине (удалить модификатор Y.CMS и установить ycms.ocmod.xml через установщик расширений). 

Замена выполняется в строках [111](https://github.com/yandex-money/yandex-money-cms-opencart2/blob/deda152d22305b7aba63d6a61d62ae1f1320885f/ycms.ocmod.xml#L111) и [117](https://github.com/yandex-money/yandex-money-cms-opencart2/blob/deda152d22305b7aba63d6a61d62ae1f1320885f/ycms.ocmod.xml#L117) соответственно.
