### ISSUE TITLE
Некорректно работает модуль

### ISSUE THREAD

**Issue by god-eater** [yandex-money/yandex-money-cms-opencart2#124]
В общем проблема в следующем, после первой неудачной попытки установки на рабочий проект, для чистоты эксперимента была развёрнут "чистый" opencart версии 2.3.0.2, после настройки ftp, после этого я установил данный модуль.
Захожу в "Каналы продвижения" и там вижу 2 одинаковым поля
![image](https://cloud.githubusercontent.com/assets/14605734/23987362/e3eaff58-0a31-11e7-80a7-3ad17d9649e7.png)
Перехожу в редактирование этого модуля и там есть такое сообщение 
![image](https://cloud.githubusercontent.com/assets/14605734/23987388/0d0bb6fc-0a32-11e7-8c6d-891c26435bab.png)
Жму на эту ссылку и получаю Ошибку доступа(Даже если открываю этот модуль через Модули/Оплата)
![image](https://cloud.githubusercontent.com/assets/14605734/23987441/4854b95c-0a32-11e7-87ea-54637773324c.png)
Все  действия выполняются от админа и администраторской группы, в настройках группы отмечены все галочки на просмотр и изменение.

**Comment by ikarmanov** [comment]
Добрый день.

Такое поведение вызвано наличием файлов модуля для двух разных версий. Попробуйте установить новую версию модуля 2.1.0, которая исправит ситуацию.
