### ISSUE TITLE
Выгружаются только категории OpenCart 2.3

### ISSUE THREAD

**Issue by donskih** [yandex-money/yandex-money-cms-opencart2#127]
Выгружаются только категории https://avartis.ru/index.php?route=feed/yamarket
Пробовал ставить выгружать все не помогает, в чем может быть проблема?

**Comment by sh2rman** [comment]
попробуйте использовать файл catalog\controller\feed\yamarket.php от версии 1.6

**Comment by donskih** [comment]
Не помогло

**Comment by ikarmanov** [comment]
Добрый день.

Необходимо для каждого продукта иметь производителя (в карточке продукта).
