### ISSUE TITLE
Ломает стандартный дизайн Раздела Заказы

### ISSUE THREAD

**Issue by yuranikspb** [yandex-money/yandex-money-cms-opencart2#129]
![123123](https://cloud.githubusercontent.com/assets/1639829/24287650/7a4d13a0-108b-11e7-9047-5e50452a0ebc.JPG)
кнопка удалить сьехала
выделить заказы ( поставить галочку) почти не возможно так как ее не видно

**Comment by ikarmanov** [comment]
Добрый день.

Сообщите версию CMS и модуля, чтобы мы смогли проверить наличие проблемы

**Comment by yuranikspb** [comment]
opencart Version 2.3.0.2 (rs.4)
Версия модуля 2.0.1

**Comment by yuranikspb** [comment]
Да но версию пишет не правильно модуля, на самом деле 2.1.0

**Comment by ikarmanov** [comment]
Спасибо. Скоро проверим повторение данной ситуации на чистой версии Opencart 2.3.0.2 (rs.4).
