### ISSUE TITLE
Обновление с 2.0.1

### ISSUE THREAD

**Issue by rim89** [yandex-money/yandex-money-cms-opencart2#130]
При попытке обновления скрипт упорно видит себя как версия 2.0.1 а 2.1.0 , удалял и автоматом и вручную ( кроме БД) - толку нету. В чем может быть проблема ?

**Comment by ikarmanov** [comment]
Добрый день.

Установка выполняется через установщик расширений Opencart? В процессе установки возникали какие-либо сообщения об ошибках?

**Comment by yuranikspb** [comment]
Подтверждаю тоже самое обновлял через установщик Opencart

**Comment by ikarmanov** [comment]
В текущей версии модуля при удалении его через административную панель происходит удаление файлов модуля. Попробуйте установить актуальную версию, удалить её и установить повторно.
