### ISSUE TITLE
Оплаченные заказы не появляются в админке

### ISSUE THREAD

**Issue by Kila14** [yandex-money/yandex-money-cms-opencart2#131]
Здравствуйте.
При оплате заказов с банковской карточки проблем нет. Заказ появляется в админке, письма отправляются. При оплате через яндекс деньги заказы в админке не появляются и письма с оплаченным статусом не отправляются. Их можно найти в "пропавших заказах" со статусом по умолчанию (не тем, который установлен для оплаченного заказа).
Оплата через модуль яндекс деньги (не яндекс касса) версия 1.1.0. Версия opencart: 2.0.3.1 и 2.3.0.2 (там используется модуль для версий 2.3, но ошибка та же).

**Comment by ikarmanov** [comment]
Добрый день.

Нам потребуется время на проверку данной ситуации.

**Comment by Kila14** [comment]
Здравствуйте.
Прошло 2 недели. Что-нибудь удалось выяснить? Может быть нужна дополнительная информация от меня?

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо за ожидание. Вам необходимо написать на cms@yamoney.ru и коллеги перенаправят ваш запрос в нужный отдел. В письме укажите номер кошелька Яндекс.Денег, дату операции.
