### ISSUE TITLE
Ошибка при нажатии кнопки "Управление заказом"

### ISSUE THREAD

**Issue by aralex** [yandex-money/yandex-money-cms-opencart2#132]
Здравствуйте!
При нажатии на кнопку "Управление заказом" в разделе "Заказы" вместо формы возврата денег появляется следующее:

```
Ошибка запроса данных об операции.

Технические подробности:
80.78.250.175
a:4:{s:6:"shopId";s:5:"55172";s:9:"requestDT";s:25:"2017-03-29T18:50:43+03:00";s:12:"outputFields";s:48:"orderNumber;invoiceId;orderSumAmount;paymentType";s:11:"orderNumber";s:3:"611";}
```

Движок - OpenCart 2.1.0.2. Ошибка стала появляться после обновления модуля с версии 1.6.1 до версии 2.1.0. При установке OCMOD-а ошибок не было. Встроенная проверка работы модуля проблем не выявляет.

**Comment by ikarmanov** [comment]
Это ошибка информирует об ответе сервиса Яндекс.Кассы с отказом.
Рекомендую обратиться в службу поддержки модуля по адресу cms@yamoney.ru. Ошибка может возникнуть из-за отсутствия доступа по MWS.
