### ISSUE TITLE
Отключение метоов доставки

### ISSUE THREAD

**Issue by urdenko** [yandex-money/yandex-money-cms-opencart2#133]
В файле admin/controller/feed/yamodule.php в есть проверка на существование модулей 

if (!file_exists(DIR_APPLICATION . 'controller/shipping/' . $value . '.php')) {
				$this->model_extension_extension->uninstall('shipping', $value);
				unset($extensions[$key]);
}

у меня этот код отключает все модули доставки и сбрасывает их настройки, потому что на моем движке ocStore 2.3.0.2 нужно писать так: 

if (!file_exists(DIR_APPLICATION . 'controller/shipping/' . $value . '.php') && !file_exists(DIR_APPLICATION . 'controller/extension/shipping/' . $value . '.php')) 

Пожалуйста, удалите хотя бы строчку 
$this->model_extension_extension->uninstall('shipping', $value); 
потому что эта операция выходит за рамки полномочий стороннего модуля

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо за информацию. Вы правы и управлением модулями доставки должен заниматься сам администратор магазина. Скоро опубликуем исправление.

**Comment by ikarmanov** [comment]
Сегодня будет опубликован фикс (версия 2.1.1.2), который исключает удаление/отключение методов доставки магазина.
