### ISSUE TITLE
Ошибка при установке

### ISSUE THREAD

**Issue by Qkoss** [yandex-money/yandex-money-cms-opencart2#134]
Здравствуйте!

Не могу поставить модуль даже на чистый OcStore  2.3.0.2.2

При установке выдает ошибку, во вложении прикрепил скрин.
При этом модуль появляется, причем сразу две штуки (скрин приложил) 
Заходя в модуль видим ошибку (скрин приложил)

Уже пять раз переустанавливал и сам движок и модуль, никак не получается. 

В чем может быть проблема? 

Заранее спасибо! 

![1](https://cloud.githubusercontent.com/assets/26418886/24831004/b40be7d2-1c99-11e7-9c9b-c64131643d78.PNG)
![222](https://cloud.githubusercontent.com/assets/26418886/24831005/b425a5aa-1c99-11e7-8fe0-c2dc572c8b18.PNG)
![1111](https://cloud.githubusercontent.com/assets/26418886/24831006/b43638d4-1c99-11e7-95f6-d9dfcf855f5f.PNG)

**Comment by bombapiter** [comment]
Да, такая же ошибка!!!!

**Comment by ikarmanov** [comment]
Добрый день.

Меняем логику установки модуля, которая позволит исключить дополнительные действия через ftp.

**Comment by ikarmanov** [comment]
Добрый день.

Рекомендую воспользоваться моим советом из #140
