### ISSUE TITLE
Не устанавливается

### ISSUE THREAD

**Issue by dmz2003** [yandex-money/yandex-money-cms-opencart2#135]
После установки в модификаторах появляется 	Y.CMS for Opencart 2.0.x - 2.3.x
В каналах продвижения ничего нет.
Ошибок нет
OC 2.3.0.2 (rs.3)

**Comment by haric655** [comment]
Такая же ерунда.

**Comment by mosmyru** [comment]
И у меня. Ай нид хэлп

**Comment by ikarmanov** [comment]
В текущей версии модуля при удалении его через административную панель происходит удаление файлов модуля. Попробуйте установить актуальную версию, удалить её и установить повторно.
