### ISSUE TITLE
Fatal error: 

### ISSUE THREAD

**Issue by m49n** [yandex-money/yandex-money-cms-opencart2#136]
Fatal error: Class 'ControllerFeedYamodule' not found in /public_html/admin/controller/feed/yamodule.php on line 3

Вот такая вот ошибка возникает после установки, при попытке перейти в настройку модуля в каналах продвижения,
Версия модуля: последняя что лежала на гите
Версия опенкарт Version 2.1.0.1

**Comment by alexmaksimov** [comment]
Same story

**Comment by ikarmanov** [comment]
Добрый день.

Воспользуйтесь моим советом из #140 и сообщите результат

**Comment by alexmaksimov** [comment]
К сожалению, ошибка сохранилась. Opencart.pro 2.1.0.2.1

**Comment by ikarmanov** [comment]
Рекомендую вручную удалить все файлы модуля. Инструкция [тут](https://github.com/yandex-money/yandex-money-cms-opencart2/blob/master/FAQ.md).

**Comment by leresist** [comment]
> Рекомендую вручную удалить все файлы модуля. Инструкция тут.
Рекомендую Вам сменить профессию и держаться подальше от компьютера. Благодаря вам обгажена репутация всего яндекса и подорвана потенциальная прибыль ввиду отсутствия рабочего модуля оплаты.

**Comment by alexmaksimov** [comment]
@ikarmanov Удалил все файлы согласно инструкции. Загрузил модуль через FTP, установил модуль через xml файл. В результате при попытке включения модуля в админке получаю ошибку:
`Fatal error: Class 'ControllerPaymentYamodule' not found in /var/www/admin/data/www/pelle-volare.com/admin/controller/payment/yamodule.php on line 2`

**Comment by BigVg** [comment]
Получаю похожую ошибку Fatal error: Class 'ControllerFeedYamodule' not found in .../admin/controller/feed/yamodule.php on line 3
Пробовал удалять и ставить разными способами, но все равно выдает эту ошибку. 
Есть решение этой проблемы?

**Comment by leresist** [comment]
Да, воспользуйтесь другим модулем

15 июл. 2017 г. 19:10 пользователь "BigVg" <notifications@github.com>
написал:

**Comment by BigVg** [comment]
Не посоветуете каким воспользоваться?

**Comment by leresist** [comment]
Я настроил уже предустановленный в ocstore модуль. Работает отлично и без
геммороя. Если у вас его нет, напишите , чуть позже смогу скинуть название

15 июл. 2017 г. 19:18 пользователь "BigVg" <notifications@github.com>
написал:

**Comment by BigVg** [comment]
У нас нет на сайте, версия ocstore старая стоит. Буду признателен если напишите название

**Comment by ikarmanov** [comment]
Добрый день.

Попробуйте обновить модуль по ссылке ниже:
[для Opencart 2.0.x-2.1.x](https://github.com/yandex-money/yandex-money-cms-opencart2/blob/master/ycms.oc20x21x.ocmod.zip?raw=true)
[для Opencart 2.2.x](https://github.com/yandex-money/yandex-money-cms-opencart2/blob/master/ycms.oc22x.ocmod.zip?raw=true)
[для Opencart 2.3.x](https://github.com/yandex-money/yandex-money-cms-opencart2/blob/master/ycms.oc23x.ocmod.zip?raw=true)

**Comment by BigVg** [comment]
Добрый день,
Переустановил модуль, сейчас модуль включается и настраивается. Но при попытке посмотреть файл (index.php?route=feed/yamarket) для выгрузки, выдает ошибку: Fatal error: Class 'ModelYamodelYamarket' not found in ..../catalog/model/yamodel/yamarket.php on line 3

**Comment by ikarmanov** [comment]
Спасибо. Поправили и это. Попробуйте обновить по ссылкам выше

**Comment by BigVg** [comment]
Обновил, вроде все работает, но полностью не тестировали еще, спасибо.
Еще вопрос, по настройке, как  я понял отфильтровать товар для выгрузки на маркет можно только по категориям? Или есть возможность выбрать только те товары которые нужно?
И будет ли работать "Заказы на Маркете" если выгружать товары на маркет не через ваш модуль "Яндекс.Маркет", а через другой, ранее установленный?

**Comment by hadoukenlol** [comment]
Здравствуйте, установил ваш модуль, а выгружаются только категории.

**Comment by ikarmanov** [comment]
**>как я понял отфильтровать товар для выгрузки на маркет можно только по категориям?** 
Вы верно поняли и на данный момент выгрузка возможна категориями или всем списком товаров. 

**>И будет ли работать "Заказы на Маркете" если выгружать товары на маркет не через ваш модуль "Яндекс.Маркет", а через другой, ранее установленный?**
Зависит от записи идентификаторов товаров и их сочетаний. У программы "Заказы на Маркете" есть тестовый режим и Вы самостоятельно сможете смоделировать заказы ваши клиентов и посмотреть на реакцию нашего модуля.

**Comment by ikarmanov** [comment]
**hadoukenlol**, добрый вечер.

Функционал бронирования не поддерживается текущей версией модуля. Мы рассмотрим его добавление в новую версию. Спасибо.

**Comment by BigVg** [comment]
Спасибо, все понял

**Comment by hadoukenlol** [comment]
А по какой причине могут выгружаться только категории?

**Comment by ikarmanov** [comment]
**>В текущей версии модуля при удалении его через административную панель происходит удаление файлов модуля. Попробуйте установить актуальную версию, удалить её и установить повторно.**
Скорее всего у товаров отсутствует производитель
