### ISSUE TITLE
Ошибка спецификации XML

### ISSUE THREAD

**Issue by Spaun91** [yandex-money/yandex-money-cms-opencart2#137]
Здравствуйте, у меня собственно ошибка при создании Yml файла, из рыл весь интернет, но решения так и не могу найти прилагаю фото ошибки:
![2017-04-25 22 01 46](https://cloud.githubusercontent.com/assets/28020190/25403025/8035ab56-2a03-11e7-8600-2a0aa2cb9d59.png)
Ссылка: http://sexstoryshop.ru/index.php?route=feed/yamarket
помогите пожалуйста)

**Comment by ikarmanov** [comment]
Добрый день.

Попробуйте сохранить содержимое http://sexstoryshop.ru/index.php?route=feed/yamarket в файл и указать этот файл Яндекс.Маркету, чтобы исключить разной нумерации строк с ошибкой. После этого сообщите текст ошибки и приложите файл прайс-листа.

**Comment by Gromy** [comment]
слишком длинное название значения тега shop, у меня такое было, потому что модуль значение берет из title самого магазина
