### ISSUE TITLE
PHP Fatal error:  Uncaught Exception

### ISSUE THREAD

**Issue by yuranikspb** [yandex-money/yandex-money-cms-opencart2#138]
ошибка возникает если выбрать оплату наличкой в  офисе на последнем этапе
заказ создается но ошибка
в истории заказов оплату яндексом не выбрать для такого заказаю
версия  2.1.0

`PHP Fatal error:  Uncaught Exception: Error: Could not load model yamodel/pokupki! in /var/www/beta/vqmod/vqcache/vq2-system_storage_modification_syste
m_engine_loader.php:59\nStack trace:\n#0 /var/www/beta/vqmod/vqcache/vq2-system_storage_modification_catalog_controller_checkout_success.php(10): Loader->model('yamodel/pokupki')\n#1 /var/www/beta/vqmod/vqcache/vq2-system_storage_modific
ation_system_engine_action.php(51): ControllerCheckoutSuccess->index()\n#2 /var/www/beta/catalog/controller/startup/router.php(25): Action->execute(Object(Registry))\n#3 /var/www/beta/vqmod/vqcache/vq2-system_storage_modification_system_
engine_action.php(51): ControllerStartupRouter->index()\n#4 /var/www/beta/system/engine/front.php(34): Action->execute(Object(Registry))\n#5 /var/www/beta/system/engine/front.php(29): Front->execute(Object(Action))\n#6 /var/www/beta/syst
em/framework.php(103): Front->dispatch(Object(Action), Object(Action))\n#7 /var/www/beta/vqmod/vqcache/vq2-system_startup.php(124): require_once('/var/www/beta/s...')\n#8 /var/www/beta/index in /var/www/beta/vqmod/vqcache/vq2-system_stor
age_modification_system_engine_loader.php on line 59`

**Comment by ikarmanov** [comment]
Воспользуйтесь моим советом из #140 и сообщите результат
