### ISSUE TITLE
Ошибка при активации 

### ISSUE THREAD

**Issue by VellBVN** [yandex-money/yandex-money-cms-opencart2#139]
Версия ocStore 2.3.0.2.2
Все делаю по инструкции https://kassa.yandex.ru/files/manual_y.cms_opencart2.pdf

на шаге
7. В списке каналов найдите «Y.CMS от Яндекс.Кассы» и нажмите «Активировать» (зеленый квадрат)
получаю ошибку
Notice: Undefined index: ya_kassa_sid in C:\OpenServer\domains\olikids.vm\admin\controller\tool\mws.php on line 18Warning: Cannot modify header information - headers already sent by (output started at C:\OpenServer\domains\ххх.vm\admin\controller\startup\error.php:34) in C:\OpenServer\domains\ххх.vm\system\library\response.php on line 12

и дальше ничего не работает. в чем может быть проблема, помогите.
Несколько раз повторял установку после восстановления, но ошибка не пропадает.

**Comment by ikarmanov** [comment]
Удалите файлы модуля (можно через [утилиту](https://yadi.sk/d/CaX0jg503HxXk8), но только если у PHP будут права на удаление этих файлов) и установите [версию 2.1.1 для Opencart 2.3.x](https://github.com/yandex-money/yandex-money-cms-opencart2/blob/master/ycms.oc23x.ocmod.zip?raw=true)

**Comment by VellBVN** [comment]
Установил.
При переходе в админке, получаю ошибку "Сайт olikids.vm выполнил переадресацию слишком много раз." и не работает.
![302redir](https://cloud.githubusercontent.com/assets/10273898/25912989/dff273fc-35c1-11e7-82c9-b5d0612c0b43.JPG)

**Comment by ikarmanov** [comment]
Пришлите журнал (лог) модификаторов после его очистки и обновления (кнопка в разделе работы с модификаторами).

**Comment by invays** [comment]
Проблема лично у меня решилась сменой категории на идентичную в версии Ocstore 2.1.0.2
