### ISSUE TITLE
Проблемы с установкой

### ISSUE THREAD

**Issue by edichome** [yandex-money/yandex-money-cms-opencart2#140]
Не советую никому использовать этот модуль.
Или откатите назад, когда все хоть как то, но работало, или вообще уберите модуль, который просто убивает только что установленный opencart.
По наивности еще и попытался обновить на одном магазине - убило тоже.
Плюс ко всему в каналах продвижения и в оплатах появляется сразу по два модуля, при попытке активации - "сервер не может обработать запрос"
Это значит, что в установочном файле теперь версии и для opencar 2 и для 2.3 и заливаются обе. Зачем? У вас же был отдельный модуль уже для opencart 2.3 (как минимум v.2.1)

**Comment by ikarmanov** [comment]
Добрый день.

Проблему выявили и [сделали](https://github.com/yandex-money/yandex-money-cms-opencart2/releases/tag/2.1.1) несколько архивов модуля, которые не меняю своей структуры каталогов динамически (в процессе установки).

**Comment by edichome** [comment]
Спасибо, будем пробовать.

**Comment by edichome** [comment]
Обновил, версия 2.3.0.2 - результат при активации модуля - "Internal serever error" не работает.
То есть может нужно сносить вчистую то что было установлено, лазить по всем каталогам и искать следы? Может что то в базе данных тоже? Но просто установкой, вопрос не решается.
Модуль не рабочий, по крайней мере для обновления, может быть на чистую систему и встанет, но нет времени пробовать все с нуля.

**Comment by mantol4ik** [comment]
Что делать?
![default](https://cloud.githubusercontent.com/assets/28677517/26028632/c7c25132-3835-11e7-91b6-f25f640bb6a7.PNG)

**Comment by ikarmanov** [comment]
Добрый день. По ошибке виду, что на сайте присутствуют старые файлы модуля.
Можно попытаться удалить все следы модуля с помощью [расширения ](https://github.com/yandex-money/yandex-money-cms-opencart2/releases/tag/2.1.1) или удалить файлы из списка ниже вручную.

Каталог `admin`:
```
        "controller/feed/yamodule.php",
        "controller/payment/yamodule.php",
        "controller/tool/mws.php",
        "model/yamodule/metrika.php",
        "model/yamodule/pokupki.php",
        "model/yamodule/return.php",
        "controller/extension/feed/yamodule.php",
        "controller/extension/payment/yamodule.php",
        "controller/extension/tool/mws.php",
        "model/extension/yamodule/metrika.php",
        "model/extension/yamodule/pokupki.php",
        "model/extension/yamodule/return.php"
```

Каталог `catalog`:
```
        "controller/feed/yamarket.php",
        "controller/payment/yamodule.php",
        "controller/yandexbuy/cart.php",
        "controller/yandexbuy/order.php",
        "model/payment/yamodule.php",
        "model/yamodel/pokupki.php",
        "model/yamodel/yamarket.php",
        "model/yamodel/yamoney.php",
        "controller/extension/feed/yamarket.php",
        "controller/extension/payment/yamodule.php",
        "controller/yandexbuy/cart.php",
        "controller/yandexbuy/order.php",
        "model/extension/payment/yamodule.php",
        "model/extension/yamodel/pokupki.php",
        "model/extension/yamodel/yamarket.php",
        "model/extension/yamodel/yamoney.php"
```

**Comment by edichome** [comment]
Нет старых файлов, даже при сносе полностью и установке на чистую систему, со стандартным шаблоном error...
Тем не менее старый модуль встает без проблем.
Какая то бесконечно длинная мука, ну нельзя столько времени и сил убивать лишь для обновления!
Либо Я.кассой никто не пользуется особо с opencart, либо еще сидят на старых версиях, либо используют другие модули, но ваш явно с проблемами.
Да и предыдущий установленный на рабочем магазине допиливали в Яндексе установив что то и поправив, не сказав , что именно. Теперь не хочется даже прикасаться, чтобы не убить случайно. Для этого ставлю на чистую платформу, чтобы когда нибудь, видимо не скоро, перенести сайт.

**Comment by ikarmanov** [comment]
Спасибо за информацию. Проверяем.

**Comment by edichome** [comment]
Вот такая ошибка при активации модуля:
<img width="500" alt="yandex" src="https://cloud.githubusercontent.com/assets/5670645/26198241/eee9d792-3bf7-11e7-93e7-cb38736d1b56.png">
А затем модуль при перезагрузке он активирован, но после попытки входа следующее:
![yandex2](https://cloud.githubusercontent.com/assets/5670645/26198395/74b9ff14-3bf8-11e7-942d-214a182b2fc2.jpg)

**Comment by kiselev-maksim** [comment]
В этой версии модулей неверно прописаны пути к моделям (нужно добавить "extension") в файлах:
catalog/controller/extension/payment/yamodule.php
в функции Callback заменить
`$this->load->model('yamodel/yamoney');`
на
`$this->load->model('**extension/**yamodel/yamoney');`
далее, везде заменить
`$this->model_yamodel_yamoney`
на
`$this->model_extension_yamodel_yamoney`

то же самое касается контроллера Яндекс.Маркет.

**Comment by edichome** [comment]
Когда нибудь появится рабочий модуль для OpenCart 2.3, чтобы просто установить и пользоваться? 
На чистой системе не работает, при активации/деактивации - Internal Error
<img width="200" alt="2017-06-05 18 36 38" src="https://cloud.githubusercontent.com/assets/5670645/26780799/04ff37b4-4a1e-11e7-914f-10fb3c54544f.png">
версию в модификаторе показывает 1.1.0 (она же прописана в ycms.ocmod.xml
Есть **скачанный в декабре модуль**, рабочий, даже тот показывет версию 2.0.0, он рабочий, только кривая страница _Продажи > Заказы_ и нет Модуль кассы.
Какая то бесконечная игра, не знаю как ставит народ, почему ставится предыдущая версия и не работает новая, но я сам не могу найти причину.
Может кто то все таки посмотрит и ответит на вопрос??

**Comment by edichome** [comment]
закройте вообще Яндекс Кассу, если некому допилить даже модуль.

**Comment by Spartakd** [comment]
Добрый день. 
Раньше все работало. 
Вылазит ошибка при заказе: Notice: Trying to get property of non-object in /home/webempir/domains/web-empire.com/public_html/ssl/catalog/controller/extension/payment/yamodule.php on line 164

Opencart: Version 2.3.0.0 (2.3.0.2-rs) Русская сборка.
Шаблон: CosyOne v2.8 - Multipurpose Opencart Theme
https://themeforest.net/item/cosyone-multipurpose-opencart-theme/9257138
