### ISSUE TITLE
Настройки редиректа для Nginx

### ISSUE THREAD

**Issue by frochdev** [yandex-money/yandex-money-cms-opencart2#142]
В инструкции по установке есть правила редиректа для Apache, но не примера для Nginx. Можете поделиться инофмарцией для Nginx?

P.s. правила для Apache:
> добавить в файл .htaccess корневого каталога сайта строку RewriteRule ^yandexbuy/([^?]*)$ index.php?route=yandexbuy/$1 [L,QSA] после строки RewriteBase /

**Comment by eightyeight** [comment]
#173
