### ISSUE TITLE
HTTP ERROR 500 при возврате на сайт после оплаты

### ISSUE THREAD

**Issue by avtovogol** [yandex-money/yandex-money-cms-opencart2#145]
Установил модуль Y.CMS для Opencart 2.3x. Настроил приём платежей на яндекс кошелёк по вашему руководству. Платёж проходит успешно, http уведомление приходит, статус заказа меняется, но при переходе по ссылке обратно в магазин выдаёт ошибку HTTP ERROR 500.
Версия последняя 2.1.1.3

**Comment by ikarmanov** [comment]
Добрый день.

Для анализа ситуации нужна ссылка, которая вызывает данную ошибку. Можете написать её тут или отправить на адрес cms@yamoney.ru с описанием проблемы. Мы поможем разобраться.
