### ISSUE TITLE
Неправильно указанный путь к модулю

### ISSUE THREAD

**Issue by gebteus** [yandex-money/yandex-money-cms-opencart2#146]
<domain>/index.php?route=checkout/success отваливается с "Fatal error: Uncaught exception 'Exception' with message 'Error: Could not load model yamodel/pokupki!'"

Модуль ищет файлы в директории /catalog/model/yamodel, но этой директории не существует, вместо этого нужные файлы лежат в /catalog/model/**extension**/yamodel/
Если скопировать директорию yamodel из /catalog/model/extension в /catalog/model, то проблема исчезает.

OpenCart 2.3.0.2

**Comment by Rusk777** [comment]
index.php?route=feed/yamodule - при попытке зайти в настройки, получаю Доступ запрещен!.
index.php?route=**extension**/feed/yamodule&token - должен быть

**Comment by ikarmanov** [comment]
Добрый день.

Рекомендую обновить модуль до версии 2.2.0, т.к. там ссылка исправлена.
