### ISSUE TITLE
Error  страница index.php?route=payment/yamodule/callback

### ISSUE THREAD

**Issue by Marselksavye** [yandex-money/yandex-money-cms-opencart2#147]
Здравствуйте показывает 
Error ошибку
Ошибка на  странице ... index.php?route=payment/yamodule/callback
**You aren't Yandex.Money.**

Яндекс Касса подключена, модуль сам при проверке работы  модуля пишет "Всё Хорошо"
можете провести тестовый платёж

**Comment by ikarmanov** [comment]
Добрый день.

Этот адрес служебный. Об этом говорится в "You aren't Yandex.Money.". Рекомендую совершить пробный платеж и посмотреть на результат.

**Comment by Marselksavye** [comment]
Спасибо )
Всё работает!
Хорошего дня
