### ISSUE TITLE
Маркет не принимает ссылку из модуля

### ISSUE THREAD

**Issue by tychkin** [yandex-money/yandex-money-cms-opencart2#149]
![2017-06-18_18-45-46](https://user-images.githubusercontent.com/29484181/27261974-b8255520-5456-11e7-8dc8-b9a03b0f3e61.png)

**Comment by jorg953** [comment]
Ошибка 404...
Перейдите по ссылке - http://skstroydom.ru/index.php?route=feed/yamarket
У вас вместо модуля страница 404

**Comment by tychkin** [comment]
Так что надо сделать чтобы все это появилось?
Настройки есть - я же вижу в админке
Сможете установить? Я уже 3 недели с этим модулем мучаюсь - никто не знает - как он должен корректно работать 
А кто знает - отправляет к вам.

**Comment by ikarmanov** [comment]
Добрый день.

Рекомендую установить новую [версию модуля 2.2.0.1](https://github.com/yandex-money/yandex-money-cms-opencart2/releases/tag/2.2.0.1) и сообщить результат.

**Comment by tychkin** [comment]
Добрый день
Не встает)))
Я уже руками в csv export сделал прайс лист для индекс маркета на 3500 позиций,
И устал мучаться с модулем,
Может быть все-таки поможете мне его поставить?
Сил нету
На форуме - нет никого - кто мог бы взяться за этот вопрос профессионально

**Comment by ikarmanov** [comment]
Рекомендую написать в службу поддержки (cms@yamoney.ru) и коллеги смогут подсказать с настройкой и установкой модуля.

**Comment by tychkin** [comment]
Добрый день.
Коллеги из поддержки забили и не отвечают на вопросы
Пытаюсь заново установить модуль - вот что выдает 

SyntaxError: JSON Parse error: Unrecognized token '<'
OK
<b>Warning</b>: ftp_chdir(): Failed to change directory. in <b>/home/i/infokrou/skstroydom.ru/public_html/admin/controller/extension/installer.php</b> on line <b>298</b>{"error":"\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u0432\u044b\u0431\u0440\u0430\u0442\u044c \u043a\u043e\u0440\u043d\u0435\u0432\u043e\u0439 \u043a\u0430\u0442\u0430\u043b\u043e\u0433 «}

Куда далее идти?

**Comment by ikarmanov** [comment]
Добрый день.

Попробуйте установить модуль после применения модификатора [QuickFix от iSense](https://www.opencart.com/index.php?route=marketplace/extension/info&member_token=B9Ikn7L8B41h1OwoZkRSNsuMEckpCHfs&extension_id=18892)

**Comment by tychkin** [comment]
Ничего не поменялось 
Придется ставить модуль от вашего конкурент - никуда не денешься,
Никто не берется устанавливать ваш модуль - даже за деньги

**Comment by ikarmanov** [comment]
**tychkin**, ошибка с ftp точно должна была пропасть. Может кэш модификаторов был старый. Попробуйте в разделе **Модификаторы** нажать кнопку **Обновить** и потом снова попытаться установить архив нашего модуля. 

Сообщите результат.
