### ISSUE TITLE
Ошибка в работе прайса Яндекс Маркета- EntityRef: expecting ';'

### ISSUE THREAD

**Issue by Marselksavye** [yandex-money/yandex-money-cms-opencart2#150]
Добрый день!
Скажите с чем связана Ошибка в работе прайса Яндекс Маркета.
error on line 247 at column 323: EntityRef: expecting ';'

**Comment by Gromy** [comment]
аналогичная проблема, есть решение?

**Comment by Gromy** [comment]
Проблему решил, проблема в инпользовании символов & амперсанта, уберите из товарных описаний символ &

**Comment by Marselksavye** [comment]
Отлично )
Спасибо Большое
