### ISSUE TITLE
Ошибка при подключении к программе "Заказ на маркете"

### ISSUE THREAD

**Issue by jorg953** [yandex-money/yandex-money-cms-opencart2#151]
URL = https://домен/yandexbuy/order/accept
Детали ошибки = unsupported media-type; nested exception is org.springframework.web.HttpMediaTypeNotSupportedException: Content type 'text/html;charset=UTF-8' not supported

<img width="656" alt="1" src="https://user-images.githubusercontent.com/29571188/27330530-7a866de0-55c2-11e7-887e-079bad4ebde8.PNG">
<img width="656" alt="1" src="https://user-images.githubusercontent.com/29571188/27330531-7a869932-55c2-11e7-9779-d14d66037b85.PNG">

Как исправить?

**Comment by ikarmanov** [comment]
Добрый день.

Обновите модуль до [версии 2.2.0.1](https://github.com/yandex-money/yandex-money-cms-opencart2/releases/tag/2.2.0.1) и сообщите результат.

**Comment by ikarmanov** [comment]
Прошу Вас написать на cms@yamoney.ru и приложить лог запроса/ответа Яндекс.Маркета (текстом, а не скрином), Мы попробуем воспроизвести данную ситуацию в тестовой среде и разобраться в причинах такого поведения. В теме письма укажите ваш сайт.

**Comment by jorg953** [comment]
Добрый день
Я отправлял письмо 25 июн в 22:11, никакого ответа нет
На этой почте никто не отвечает
