### ISSUE TITLE
Как обновить модуль?

### ISSUE THREAD

**Issue by dderzhko** [yandex-money/yandex-money-cms-opencart2#152]
Здравствуйте! Подскажите как обновить модуль. Понимаю что это наверно "очень просто", но не хочу накосячить и потом переделывать.

**Comment by ikarmanov** [comment]
Добрый день.

Обновление модуля выполняется таким же образом, как и его установка.
Вам достаточно:
1. Настроить магазин на CMS Opencart на работу по FTP (или можно использовать [QuickFix от iSense](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=18892))
2. [Скачать](https://github.com/yandex-money/yandex-money-cms-opencart2/releases/tag/2.2.0.1) архив модуля для Вашей версии Opencart (под фразой Downloads)
3. Зайти в административную панель сайта и в разделе "Расширения"-"Установка расширений" указать загруженный архив
4. Активация и настройка подробнее описана на [сайте Яндекс.Кассы](https://kassa.yandex.ru/manuals/manual_y.cms_opencart2.html)
