### ISSUE TITLE
Ошибка при попытке сохранить на вкладке метрики

### ISSUE THREAD

**Issue by fster29** [yandex-money/yandex-money-cms-opencart2#154]
При переходе на вкладку метрики, не изменяя или изменяя начальные настройки и нажатии кнопки сохранить вылетают следующие ошибки:

Fatal error: Uncaught exception 'Exception' with message 'Error: Could not load model yamodule/metrika!' in W:\domains\test.ru\system\engine\loader.php:59 Stack trace: #0 [internal function]: Loader->model('yamodule/metrik...') #1 W:\domains\test.ru\system\library\agoo\loader.php(140): call_user_func_array(Array, Array) #2 W:\domains\test.ru\admin\controller\extension\feed\yamodule.php(284): agooLoader->__call('model', Array) #3 W:\domains\test.ru\admin\controller\extension\feed\yamodule.php(284): agooLoader->model('yamodule/metrik...') #4 W:\domains\test.ru\admin\controller\extension\feed\yamodule.php(519): ControllerFeedYamodule->processSave() #5 [internal function]: ControllerFeedYamodule->index() #6 W:\domains\test.ru\system\engine\action.php(51): call_user_func_array(Array, Array) #7 W:\domains\test.ru\admin\controller\startup\router.php(26): Action->execute(Object(Registry), Array) #8 [internal function]: ControllerStartupRouter->index() #9 W:\domains\ts in W:\domains\test.ru\system\engine\loader.php on line 59

Ставил текущую версию модуля Y.CMS от Яндекс.Кассы (2.2.0) 
Opencart 2.3.0.2

Предыдущие версии на движке 2.1 работают нормально. Как на хостинге, так и на OpenServer

на 2.1 соответсвующая версия работает отлично

**Comment by ikarmanov** [comment]
Спасибо за информацию.
Попробуйте обновить модуль до [2.2.0.1](https://github.com/yandex-money/yandex-money-cms-opencart2/releases/tag/2.2.0.1)
