### ISSUE TITLE
 Ссылка для выгрузки товаров на Маркет для 2.3

### ISSUE THREAD

**Issue by fster29** [yandex-money/yandex-money-cms-opencart2#155]
Ссылка для выгрузки товаров на Маркет для 2.3 в версии 2.2.0.1 имеет вид: **https://test.ru/index.php?route=feed/yamarket**

а надо: **https://test.ru/index.php?route=extension/feed/yamarket**

И не плохо бы иметь возможность её скопировать, а то в ручную набивать в форме яндекса не удобно.

**Comment by ikarmanov** [comment]
Спасибо. Проверяем

**Comment by ikarmanov** [comment]
В новой версии файлов модуля исправили. Спасибо.
