### ISSUE TITLE
Не работают стандартные модули оплаты

### ISSUE THREAD

**Issue by pmz2017** [yandex-money/yandex-money-cms-opencart2#156]
Добрый день!
Всё хорошо но! Когда устанавливаешь ваш модуль на 2.3.0.2 стандартные модули оплаты перестают работать! такой модуль как "Оплата при доставке"

Чистый движок, последняя версия вашего модуля. при завершении оформления заказа, появляется ошибка "
Fatal error: Uncaught exception 'Exception' with message 'Error: Could not load model yamodel/pokupki!' in /home/koptilnya/xn----8sblojdekghl0b0ik0c.xn--p1ai/docs/system/storage/modification/system/engine/loader.php:59 Stack trace: #0 /home/koptilnya/xn----8sblojdekghl0b0ik0c.xn--p1ai/docs/system/storage/modification/catalog/controller/checkout/success.php(7): Loader->model('yamodel/pokupki') #1 [internal function]: ControllerCheckoutSuccess->index() #2 /home/koptilnya/xn----8sblojdekghl0b0ik0c.xn--p1ai/docs/system/storage/modification/system/engine/action.php(51): call_user_func_array(Array, Array) #3 /home/koptilnya/xn----8sblojdekghl0b0ik0c.xn--p1ai/docs/catalog/controller/startup/router.php(25): Action->execute(Object(Registry)) #4 [internal function]: ControllerStartupRouter->index() #5 /home/koptilnya/xn----8sblojdekghl0b0ik0c.xn--p1ai/docs/system/storage/modification/system/engine/action.php(51): call_user_func_array(Array, Array) #6 /home/koptilnya/xn----8sblojdekghl0b0ik0c.xn--p1ai/docs/system/engine/front.php(34 in /home/koptilnya/xn----8sblojdekghl0b0ik0c.xn--p1ai/docs/system/storage/modification/system/engine/loader.php on line 59 "

в логах "2017-07-04 23:33:01 - PHP Notice:  Undefined index: ya_kassa_sid in /home/koptilnya/xn----8sblojdekghl0b0ik0c.xn--p1ai/docs/admin/controller/tool/mws.php on line 18
2017-07-04 23:38:08 - callback:  request a:15:{s:5:"route";s:35:"extension/payment/yamodule/callback";s:9:"invoiceId";s:3:"123";s:11:"orderNumber";s:1:"1";s:14:"orderSumAmount";s:5:"10.00";s:13:"shopArticleId";s:1:"1";s:11:"paymentType";s:2:"PC";s:6:"action";s:10:"checkOrder";s:6:"shopId";s:5:"12345";s:4:"scid";s:5:"54321";s:18:"shopSumBankPaycash";s:0:"";s:22:"shopSumCurrencyPaycash";s:0:"";s:19:"orderSumBankPaycash";s:0:"";s:23:"orderSumCurrencyPaycash";s:0:"";s:14:"customerNumber";s:0:"";s:3:"md5";s:0:"";}

2017-07-04 23:38:08 - callback:  orderid=1
"

Есть варианты решения? или временное решение? Может замена стандартных способов оплаты?

**Comment by ikarmanov** [comment]
Проблема исправлена через файл модификатора, который мы обновили в [архивах модулей](https://github.com/yandex-money/yandex-money-cms-opencart2/commit/d46ee8cb50501f5a40c282121b528fbfbc3adb2a)
