### ISSUE TITLE
Подключение своего ФР (54-ФЗ) к модулу и Яндекс Кассе

### ISSUE THREAD

**Issue by sunlit2000** [yandex-money/yandex-money-cms-opencart2#157]
Доброго дня.
Обновил модуль до 2.2.0.1 (Opencart.PRO Версия 2.1.0.2.2). Имею ФР АТОЛ FPrint-22ПТК (54-ФЗ).
Думаю как подружить, но начали появляться вопросы. Первый момент, как в интерфейсе админки модуля корректно настроить взаимодействие с сервисом ЯКассы - нигде не описано к сожалению (или не нашел) - ткните пожалуйста в URL.
Дочитался до того, что модуль должен передавать ym_merchant_receipt, но я этого параметра не наблюдаю.
Так же не понятно, как настроить поля в приложенном скрине.
![help](https://user-images.githubusercontent.com/10777331/27961567-d467e8ac-6337-11e7-99dc-0265e8ca8eb5.jpg)

**Comment by ikarmanov** [comment]
Добрый день.

Можете пояснить каким образом АТОЛ FPrint-22ПТК (54-ФЗ) будет обмениваться информацией с вашим сайтом? 
Наш модуль отправляет данные состава чека в Яндекс.Кассу при оплате заказа (тоже через Яндекс.Кассу), а Яндекс.Касса отправляет данные партнеру (например, АТОЛ) и уже партнер отправляет данные состава чека дальше.

**Comment by sunlit2000** [comment]
Пока я рассматриваю вопрос гипотетически. Наверняка придется делать клиент-серверное приложение на подобии решения от Битрикса, которое при получении пакета от CMS через драйвер будет на ФР чек печатать.
Хотелось бы ответ по остальным вопросам получить

**Comment by ikarmanov** [comment]
Цитата из п.9 нашей [инструкции](https://kassa.yandex.ru/manuals/manual_y.cms_opencart2.html#section3):

> Если нужно, включите отправку данных для чеков. Это настройка для тех, кто работает с решением Кассы для 54-ФЗ.
> Для чека потребуется ставка НДС: если вы включили отправку данных для чеков, модуль предложит сопоставить ставки в вашем магазине и ставки в Кассе.

Т.е. Вам необходимо создать ставки НДС в вашем магазине, если сейчас они не созданы. Подумаем над тем, чтобы предупреждать об этом в самом интерфейсе настроек модуля
