### ISSUE TITLE
класс не найден

### ISSUE THREAD

**Issue by srt56** [yandex-money/yandex-money-cms-opencart2#158]
Fatal error: Class 'ControllerPaymentYamodule' not found in /www/ural432/admin/controller/extension/payment/yamodule.php on line 2

файлы все на своих местах
ошибка вываливается при попытке редактирования библиотеки
![opencart](https://user-images.githubusercontent.com/6491418/28053451-285409da-6619-11e7-8f93-356f4f0378e2.png)

**Comment by alexmaksimov** [comment]
Тоже само

**Comment by ikarmanov** [comment]
Добрый день.

Попробуйте обновить модуль по ссылке ниже:
[для Opencart 2.0.x-2.1.x](https://github.com/yandex-money/yandex-money-cms-opencart2/blob/master/ycms.oc20x21x.ocmod.zip?raw=true)
[для Opencart 2.2.x](https://github.com/yandex-money/yandex-money-cms-opencart2/blob/master/ycms.oc22x.ocmod.zip?raw=true)
[для Opencart 2.3.x](https://github.com/yandex-money/yandex-money-cms-opencart2/blob/master/ycms.oc23x.ocmod.zip?raw=true)

**Comment by srt56** [comment]
Здравствуйте
ошибка пропала, настройки модуля открываются, завтра попробую настроить

**Comment by ikarmanov** [comment]
Спасибо за информацию и выбор нашего модуля. Обращение закрываем. Если будут пожелания/ замечания, то можете создать новое issue и мы его рассмотрим.
