### ISSUE TITLE
Ошибка после обновления модуля

### ISSUE THREAD

**Issue by Warenickk** [yandex-money/yandex-money-cms-opencart2#159]
Добрый день!

Имеется ocStore 2.1.0.2.1, обновил модуль до последней версии с поддержкой онлайн касс, при подтверждении оформления заказа появляется ошибка:
Notice
: Undefined index: shipping_method in
/var/www/ruskardan.ru/catalog/controller/payment/yamodule.php
on line
47

**Comment by actofgod** [comment]
Исправлено в релизе 2.2.3
