### ISSUE TITLE
54-фз ym_merchant_receipt

### ISSUE THREAD

**Issue by Alexmsk11** [yandex-money/yandex-money-cms-opencart2#160]
opencart 2.2.0.0
Y.CMS от Яндекс.Кассы (2.2.0.1)

проблема в том что, в параметре ym_merchant_receipt передается только customerContact, других данных нет, в чем может быть проблема???

paymentType:
shopid:63ххх
scid:59ххх
orderNumber:12ххх
sum:3120.00
customerNumber:test890@test890.ru
shopSuccessURL:https://хххххх/shop/index.php?route=checkout/success
shopFailURL:https://хххххх/shop/index.php?route=checkout/failure
ym_merchant_receipt:{"customerContact":"test890@test890.ru","items":[]}
cps_phone:89111111111
cps_email:test890@test890.ru
cms_name:ya_opencart2

**Comment by ikarmanov** [comment]
Добрый день.

Проблему устранили. Прошу вас установить модуль из обновленного архива.
