### ISSUE TITLE
Не работает отправление счета по email

### ISSUE THREAD

**Issue by NuclearBeam** [yandex-money/yandex-money-cms-opencart2#170]
Деградация ф-льности. Не работает выставление счета по емейл в последних версиях модуля

**Comment by ikarmanov** [comment]
Добрый день. 
Опишите ситуацию подробней.

**Comment by NuclearBeam** [comment]
Функциональность модуля "выставление счета по емейл", отключена в модуле, о чем свидетельствует сообщение об ошибке что функциональность отключена в связи с 54-м ФЗ.

Это делает фактичестки на 50% бесполезным и сам модуль и сопутствующие услуги яндекса

**Comment by ostulov** [comment]
На текущий момент функционал выставления счетов из модуля работает. Для оперативной помощи рекомендуем обращаться в службу поддержки по почте cms@yamoney.ru
