### ISSUE TITLE
Заказ на маркете.

### ISSUE THREAD

**Issue by Xeenus** [yandex-money/yandex-money-cms-opencart2#172]
Ошибка
Детали ошибки = validate error: delivery options is empty but there are items to be delivered

Ответ от сервера
{"cart":{"items":[{"feedId":472692,"offerId":"2636","price":0,"count":1,"delivery":true}],"deliveryOptions":[],"paymentMethods":["YANDEX","CASH_ON_DELIVERY","CARD_ON_DELIVERY"]}}

Также нулевая цена, хотя в фиде цена верная. Фид формируется не вашим модулем, сам фид корректный в маркете работаем по CPC по нему

**Comment by ikarmanov** [comment]
Добрый день.

Ошибка вызвана отсутствием опций доставки для данного заказа. Для решения проблемы прошу вас обновить [новую версию](https://yadi.sk/d/hsvmJMOo3Lk86h) файла `catalog/controller/yandexbuy/cart.php`

**Comment by Xeenus** [comment]
Добрый день, ошибка осталась также
URL = ***/yandexbuy/cart
Параметры URL: auth-token=***
Детали ошибки = validate error: delivery options is empty but there are items to be delivered

Доп информация:
Ocstore 2.3.0.2.1
Установлен модуль Доставка плюс.

Также при обновлении модуля в админке пропали пункты с доставкой, обновлял около недели назад, на старой версии модуля они были( те что идут в конце в настройках)
Если нужна какая-то доп информация, сообщите плиз

**Comment by Xeenus** [comment]
Добрый день.
Есть новости?

**Comment by Xeenus** [comment]
Прошел почти месяц...
Если исправлений не будет, вы скажите, будем искать решение у других разработчиков
