### ISSUE TITLE
Ошибка в ответе API  Undefined index: yandex_delivery

### ISSUE THREAD

**Issue by poulsg** [yandex-money/yandex-money-cms-opencart2#179]
Подскажите пожалуйста как решить данную проблему.
При самопроверке (создании проверочного заказа) перед тем как начать работать с заказами на Яндекс.Маркете по CPA через CMS Opencart 2.2.0 возникает ошибка "UNSUPPORTED_MEDIA_TYPE", причина которой как я понимаю является примечание в передаваемом объекте (массиве данных)
приведенном ниже.
Не понятно откуда берется index yandex_delivery и почему он не определен.
Спасибо.

<b>Notice</b>: Undefined index: yandex_delivery in <b>/home/b/bezikoe3/seventhgeneration.ru/public_html/catalog/controller/yandexbuy/cart.php</b> on line <b>208</b>{"cart":{"items":[{"feedId":457564,"offerId":"54","price":1340,"count":1,"delivery":true}],"deliveryOptions":[{"id":"39","serviceName":"\u0421\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437","type":"PICKUP","price":0,"dates":{"fromDate":"27-09-2017","toDate":"27-09-2017"},"outlets":[{"id":540993}]},{"id":"40","serviceName":"\u0421\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437","type":"PICKUP","price":0,"dates":{"fromDate":"27-09-2017","toDate":"27-09-2017"},"outlets":[{"id":540993}]},{"id":"50","serviceName":"\u042f\u043d\u0434\u0435\u043a\u0441.\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430","type":"DELIVERY","price":0,"dates":{"fromDate":"27-09-2017","toDate":"27-09-2017"}}],"paymentMethods":["YANDEX","CASH_ON_DELIVERY","CARD_ON_DELIVERY"]}}

**Comment by ikarmanov** [comment]
Добрый день.

У вас активирована доставка с кодом yandex_delivery, но наш модуль не может подключить модель для работы с этой доставкой.
