### ISSUE TITLE
Ошибка спецификации XML

### ISSUE THREAD

**Issue by Alexey1008** [yandex-money/yandex-money-cms-opencart2#180]
Доброго дня!

Делаем экспорт через ваш модуль для ОС. Появляется ошибка:
 
Ошибка спецификации XML
 Приведите прайс-лист в соответствие с техническими требованиями выбранного формата (YML, текстовый, Excel). Обратите внимание на указание элементов внутри тега <shop>
 СтрокаСтолбецНеверное значение
 6410—
 
 url экспорта https://aquaprint.ru/index.php?route=feed/yamarket

Система ОС2.1

Помогите разобраться. Заранее спасибо!

**Comment by ikarmanov** [comment]
Добрый день.

Для оперативной поддержки рекомендую обращаться по адресу cms@yamoney.ru.
В файле https://aquaprint.ru/index.php?route=feed/yamarket вижу только чуть больше 2000 строк.
