### ISSUE TITLE
не работает на 3 версии

### ISSUE THREAD

**Issue by businessera** [yandex-money/yandex-money-cms-opencart2#181]
ругается на права

**Comment by ikarmanov** [comment]
Добрый день.

Мы готовим новую версию модуля, которая будет совместима с Opencart 3.x. Нужно немного подождать.

**Comment by optimlab** [comment]
Полгода прошло! Что для разработчиков Яндекс "немного"?

**Comment by ostulov** [comment]
Модуль для Opencart3 размещен здесь https://github.com/yandex-money/yandex-money-ycms-opencart3
