### ISSUE TITLE
Нет возможности задать по умолчанию способ оплаты

### ISSUE THREAD

**Issue by pmz2017** [yandex-money/yandex-money-cms-opencart2#183]
Добрый день! Нет возможности задать по умолчанию способ оплаты, при установке настроек по  
сценарию оплаты " Выбор способа оплаты на стороне магазина"
Модуль страницы оплаты:

AJAX Quick Checkout (One Page Checkout, Fast Checkout)

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=9132&filter_search=AJAX%20Quick%20Checkout

![image](https://user-images.githubusercontent.com/29901965/31613307-5fe3d4a2-b28b-11e7-9be4-391dcf12bda4.png)

**Comment by ikarmanov** [comment]
Добрый день.

Текущая версия модуля не позволяет определять метод оплаты по умолчанию. Рекомендуем использовать сценарий выбора метода оплаты на стороне Яндекс.Кассы.
