### ISSUE TITLE
Яндекс.Касса: Управление заказами Электронная подпись на сертификат

### ISSUE THREAD

**Issue by itshaman** [yandex-money/yandex-money-cms-opencart2#185]
Уже недели две пытаемся подключить этот модуль для нормальной работы с заказами. В процессе настройки обновили модуль до версии Y.CMS от Яндекс.Кассы (2.2.0.1)  именно её рекомендует Яндекс для OpenCart 2.3.*.* 
Заполнили заявку отправили ждали около 5 дней, наконец получили ответ от менеджеров с вложением  сертификата. Попытались вставить его в модуль - не вышло. Разбираемся = Электронная подпись на сертификат обновляется при обновлении страницы, каждый раз новая.
Помогите разобраться 
![default](https://user-images.githubusercontent.com/16690535/31893719-eab82680-b814-11e7-8692-5531177f9ca2.JPG)

**Comment by ikarmanov** [comment]
Добрый день.

Мы получили информацию о проблеме на cms@yamoney.ru и уже подготовили исправление. Сегодня/завтра обновим модуль.

**Comment by itshaman** [comment]
Спасибо за поддержку. 
Баг устраняется правкой файла. Цитирую ответ поддержки
"Добрый день!
Для решения проблемы необходимо строку 559 из файла admin/controller/feed/yamodule.php заменить с
if (count($data['mws_global_error'])==0) $this->load->controller('tool/mws/generate');
на
if (count($data['mws_global_error'])==0 && $this->config->get('yamodule_mws_csr_sign')=='') $this->load->controller('tool/mws/generate');
"
От себя добавлю
если по пути 
/admin/controller/feed/yamodule.php файл не обнаружен ищем тут
/admin/controller/extension/feed/yamodule.php
Строка в блоке //MWS

Еще раз спасибо
