### ISSUE TITLE
проблема с ocStore 2.1.0.2.1

### ISSUE THREAD

**Issue by incazzato** [yandex-money/yandex-money-cms-opencart2#189]
включили отправку чеков и хана. ничего более не пашет [client 185.111.165.168:52786] PHP Fatal error:  Uncaught Error: Call to a member function getQuantity() on null in /home/admin/web/combearzon.ru/public_html/catalog/model/yamodel/YandexMoneyReceipt.php:211\nStack trace:\n#0 /home/admin/web/combearzon.ru/public_html/catalog/controller/payment/yamodule.php(102): YandexMoneyReceipt->normalize('17745.00')\n#1 /home/admin/web/combearzon.ru/public_html/system/storage/modification/system/engine/loader.php(42): ControllerPaymentYamodule->index(Array)\n#2 /home/admin/web/combearzon.ru/public_html/system/storage/modification/catalog/controller/account/order.php(364): Loader->controller('payment/yamodul...')\n#3 /home/admin/web/combearzon.ru/public_html/system/storage/modification/system/engine/action.php(46): ControllerAccountOrder->info(Array)\n#4 /home/admin/web/combearzon.ru/public_html/system/engine/front.php(34): Action->execute(Object(Registry))\n#5 /home/admin/web/combearzon.ru/public_html/system/engine/front.php(29): Front->execute(Object(Action))\n#6 /home/admin/web/combearzon.ru/public_html/index.php(284): Front-> in /home/admin/web/combearzon.ru/public_html/catalog/model/yamodel/YandexMoneyReceipt.php on line 211, referer: https://combearzon.ru/history/

**Comment by actofgod** [comment]
Ошибка исправлена в релизе 2.2.3

**Comment by incazzato** [comment]
после обновления перенаправляет на страницу Яндекс Денег при оплате картой
