### ISSUE TITLE
Яндекс.Маркет: добавление TypePrefix в yml выгрузку товаров

### ISSUE THREAD

**Issue by Izrajk** [yandex-money/yandex-money-cms-opencart2#191]
Добрый день, 

Проблема: Яндекс.Маркет рекомендует добавлять в yml выгрузку товаров TypePrefix. 

На данный момент, я использую, Y.CMS от Яндекс.Кассы (2.2.3).
Я смог дойти до того, что в файле **catalog/controller/feed/yamrket.php**, в цикле перебора `$product`
дописал `$data['typePrefix'] = $category['name'];` и добавил в функцию `add_offer` это поле 

`$allowed = array(
            'url', 'price', 'oldprice', 'currencyId', 'categoryId', 'picture', 'store', 'pickup', 'delivery',
            'name', 'vendor', 'vendorCode', 'model', 'description', 'typePrefix','sales_notes','oldprice',
            'delivery-options','downloadable', 'weight', 'dimensions', 'param', 'country_of_origin'
        );`

В yml выгрузке, появляется поле TypePrefix, но оно дублируется для всех значений и берётся имя из неактивной категории. 

Вопрос: как мне нужно поменять строку  `$data['typePrefix'] = $category['name'];`, чтобы категория не дублировалась, а назначалась в которую входит товар, т.е в последнюю категорию?

PS. Самое странное, что во всём интернете, я не нашел, ничего, что касалось бы решением этой проблемы.

**Comment by Izrajk** [comment]
Спасибо, за бурное обсуждение проблемы с которой сталкивается каждый пользователь вашего модуля.

**Comment by gladkyby** [comment]
> В yml выгрузке, появляется поле TypePrefix, но оно дублируется для всех значений и берётся имя из неактивной категории.

Категория берется первая по алфавиту. Вот [тут ](https://opencartforum.com/topic/62962-vyvod-php-zaprosa-v-yml-fayl/)попытались решить проблему

Как вариант, можете добавить атрибут `typePrifix` к товарам и потом вывести его по [этому примеру](https://github.com/yandex-money/yandex-money-cms-opencart2/issues/119)

**Comment by Tercius** [comment]
Добрый день, установил ваш модуль, в принципе почти со всем разобрался, единственное что маркет видимо изменил интеграцию с яндекс кассой, теперь там не используется password и scid. Но вопрос в другом, как добавить в переменную product еще одно поле(значение) из бд, а конкретно интересует что бы модуль загружал кроме модели, названия товара, и описания, еще и поле например mpn.

**Comment by Isa3v** [comment]
foreach ($categories as $category) {
                if ($category['category_id'] == $product['category_id']) {
                    foreach ($categories as $category_2) {
                        if($category['parent_id'] == $category_2['category_id']){
                           $data['typePrefix'] =  $category_2['name'];
                        }
                    }
                }
            }

Лучше способа я не придумал получить родительскую категорию, категории товара. 
Само собой если убрать 2 foreach получаем просто категорию товара.
Вставлял, где перечисляются $data['...']
