### ISSUE TITLE
Заказ на маркете не работает корректно. Не используйте этот модуль

### ISSUE THREAD

**Issue by y3k3000** [yandex-money/yandex-money-cms-opencart2#194]
Поддержка нулевая. В итоге по заказу на маркете ушел в trimpo.org
МОДУЛЬ НЕ РАБОТАЕТ КОРРЕКТНО С ЗАКАЗОМ НА МАРКЕТЕ.
НЕ ИСПОЛЬЗУЙТЕ ЕГО ДЛЯ ЭТИХ ЦЕЛЕЙ.
Как итог использования модуля - маркет отключил от программы. Потерянные заказы. Жалобы покупателей. Негатив по срокам доставки.
Спасибо разработчикам.

**Comment by ostulov** [comment]
Программа "Заказы на Маркете" закрыта.
Если у Вас возникают проблемы с модулем, просьба написать на cms@yamoney.ru с подробностями.
