### ISSUE TITLE
Не появляется кнопка "Выставление счетов" я.касса

### ISSUE THREAD

**Issue by SegolevD** [yandex-money/yandex-money-cms-opencart2#196]
Opencart - 2.0.3
Y.CMS for Opencart 2.0.x - 2.3.x -2.0.0

Всё делаю по инструкции, включаю выставление счетов.
Оранжевая иконка в админке на странице заказов не появляется.
Ошибок при установке модуля в логах модификаторов нету.

Как выставить счет то?

**Comment by ostulov** [comment]
Для оперативной помощи рекомендуем обращаться в службу поддержки по почте cms@yamoney.ru
