### ISSUE TITLE
Маленькие изображения

### ISSUE THREAD

**Issue by abbasovalex** [yandex-money/yandex-money-cms-opencart2#197]
Добрый день! Подскажите, есть ли возможность устанавливать большие картинки. Сейчас модуль выгружает очень мелкие.

**Comment by Isa3v** [comment]
$url = str_replace('&amp;', '&', $this->model_tool_image->resize($localName, 600, 600)); 600х600 это конвертируемый размер. Если у тебя еще меньше, то копай в самой cms
