### ISSUE TITLE
яндекс маркет не работает

### ISSUE THREAD

**Issue by daytovar** [yandex-money/yandex-money-cms-opencart2#199]
не могу настроить яндекс маркет, все по инструкции, в чем причина не могу разобрать

**Comment by daytovar** [comment]
после установки не нашел код не в стандартном, не в текущем шаблоне
куда сейчас прописывается код, так же в footer.tpl?
счетчик не работает

**Comment by mav84** [comment]
удалось запустить выгрузку товаров на маркет? у меня почему то предложения не попадают в выгрузку

**Comment by ostulov** [comment]
Добрый день!
Для оперативной поддержки рекомендую обращаться по адресу cms@yamoney.ru. Также в письме приложите подробное описание, что именно у Вас не получается.
