### ISSUE TITLE
ошибка при попытке оформить заказ

### ISSUE THREAD

**Issue by vicgor** [yandex-money/yandex-money-cms-opencart2#2]
При оформлении заказа получаю сообщение

Notice: Error: Could not load model /var/www/shop17i7/catalog/model/payment/yamodule.php! in /var/www/shop17i7/system/modification/system/engine/loader.php on line 24

**Comment by serenya04** [comment]
Аналогичная проблема

**Comment by Red-Lolik** [comment]
Аналогично.

**Comment by ded100let** [comment]
Привет я автор. потерпите несколько дней, выходит офиц. версия. эта с ошибкой.
она появится в оф. git yandex

**Comment by ded100let** [comment]
Перекачайте модуль. всё обновлено.

**Comment by serenya04** [comment]
А есть ли возможность переделать yamodule_metrika.xml для OCMOD. Я так понимаю официального vqmod для opencart2 нет

**Comment by ded100let** [comment]
Внимание! Если вы хотите использовать p2p вам сначала необходимо зарегистрировать приложение на странице https://tech.yandex.ru/money/doc/dg/tasks/register-client-docpage/ есть инструкция.

Для сервисов Метрика и Покупки на странице https://tech.yandex.ru/oauth/doc/dg/tasks/register-client-docpage/ Все необходимые ссылки вы найдёте в настройках модуля!

Также для работы метрика необходим vqmod https://code.google.com/p/vqmod/wiki/Install_OpenCart видео по установке https://code.google.com/p/vqmod/downloads/list Ссылки на vqmod.

на счёт OCMOD я сейчас посмотрю.

**Comment by ded100let** [comment]
там не такой сложный xml так что реально. но чуть позже

**Comment by Forsakenrox** [comment]
Ява выдаёт алерты - Internal server error дважды при выборе способа оплаты Яндекс.Деньги и нажатии на "продолжить" 04.04.2015 сейчас

**Comment by ded100let** [comment]
ссылку покажи

**Comment by Forsakenrox** [comment]
http://84.52.94.83
Можно сделать тестовый заказ и проверить что не работает.

**Comment by ded100let** [comment]
я вижу 500 ошибку. хз почему. включи отображение ошибок.

**Comment by Forsakenrox** [comment]
http://hkar.ru/A5Vm вот скриншот
не знаю как можно включить  отображение ошибок в JS, по-моему только алертами это и возможно.

**Comment by ded100let** [comment]
не в js а php. Проблема в php

**Comment by Forsakenrox** [comment]
В php отображение ошибок включенно - появляются вверху страницы если таковые имеются

**Comment by Forsakenrox** [comment]
Вообще шаблон стандартный, в контроллеры я не лез, другие (встроенные) способы оплаты работают корректно, я вот от яндекса брыкается.

**Comment by ded100let** [comment]
Включите отображение ошибок в админке и в index.php пропиши 
сделай так в начале
<?php
ini_set('display_errors', 1);
ini_set('log_errors', 1);
error_reporting(E_ALL);

**Comment by ded100let** [comment]
ошибка 500 ajax запроса.

**Comment by ded100let** [comment]
всё, я увидел. Возьмите модуль отсюда попробуйте. просто подмени файлы.
https://github.com/ded100let/yandex-money-cms-opencart2

**Comment by Forsakenrox** [comment]
там лишняя скобка, можно попробовать просто убрать, щас оба варианта проверю

**Comment by vicgor** [comment]
Parse error: syntax error, unexpected '}' in /usr/share/nginx/html/catalog/view/theme/default/template/payment/yamodule.tpl on line 48

**Comment by ded100let** [comment]
я посмотрел, у меня всё на месте... подмени файлы попробуй.

**Comment by Forsakenrox** [comment]
Подменил - всё по старому

**Comment by ded100let** [comment]
Не понятно. файлы все на месте... и верны. пиши мне в скайп.  d-link570 и пиши ftp и админку

**Comment by vicgor** [comment]
надо кэш чистить
