### ISSUE TITLE
не выгружаются offer в Маркет

### ISSUE THREAD

**Issue by mav84** [yandex-money/yandex-money-cms-opencart2#200]
Файл формируется без товарных предложений
![image](https://user-images.githubusercontent.com/17058656/36718626-0f6a3f12-1bd5-11e8-9ff4-0f3974319db5.png)

настройки сейчас такие (пробовал по-разному)
![image](https://user-images.githubusercontent.com/17058656/36718680-42aecbd6-1bd5-11e8-9bca-c7a0990687dd.png)

**Comment by mav84** [comment]
Ошибка проявляется когда только 1 товар активный и 1 категория выгружается

**Comment by invays** [comment]
В файле catalog/controller/feed/yamarket.php найти строку

$products = $this->model_yamodel_yamarket->getProducts($ids_cat, true);
и в ней заменить true на false

**Comment by ostulov** [comment]
Добрый день!
Для решения данной проблемы Вам необходимо в карточках товара указать производителя.
