### ISSUE TITLE
301 Moved Permanently

### ISSUE THREAD

**Issue by lennt92** [yandex-money/yandex-money-cms-opencart2#201]
ошибка при тестовом заказе 

URL = https://site.ru/yandexbuy/cart
Параметры URL: auth-token=66935451F....B02
Детали ошибки = 301 Moved Permanently

**Comment by ostulov** [comment]
Добрый день!
Для решения данной проблемы Вам необходимо:
- Для Apache: добавить в файл .htaccess корневого каталога сайта строку RewriteRule ^yandexbuy/([^?]*)$ index.php?route=yandexbuy/$1 [L,QSA] после строки RewriteBase /
- Для Nginx: добавить в блок server конфига nginx location /yandexbuy { rewrite ^/yandexbuy/([^?]*)$ /index.php?route=yandexbuy/$1 last; }
