### ISSUE TITLE
Новый ecommerce-код для Метрики (27.03.2018)

### ISSUE THREAD

**Issue by skovorodka** [yandex-money/yandex-money-cms-opencart2#202]
Пора обновляться: устаревший ecommerce-код скоро прекратит работу...
https://yandex.ru/blog/metrika/pora-obnovlyatsya-ustarevshiy-ecommerce-kod-skoro-prekratit-rabotu

Будет ли соответствующее обновление до 27 марта?

**Comment by ostulov** [comment]
Добрый день!

Да, в ближайшее время выйдет обновленная версия модуля, которая учитывает эти изменения.
