### ISSUE TITLE
Сделать значение атрибута avaliable = true

### ISSUE THREAD

**Issue by pixelset** [yandex-money/yandex-money-cms-opencart2#208]
Добрый день. Подскажите, пожалуйста, как сделать так, чтобы значение атрибута available="false" были true?﻿
 
Сейчас выгружает товары, но для всех товаров атрибут available имеет значение false, хотя в карточках товара остаток 999.
 
Спасибо.﻿﻿

**Comment by ostulov** [comment]
Необходимо на вкладке "Яндекс.Маркет" установить "Срок доставки в пункт самовывоза" в значение "Определяется самостоятельно".
