### ISSUE TITLE
Знаю 3 серьезных недостатка модуля

### ISSUE THREAD

**Issue by mak200** [yandex-money/yandex-money-cms-opencart2#22]
Знаю 3 серьезных недостатка модуля:

1. В магазине в процессе оплаты заполняются поля "Имя, Отчество:", "Фамилия:", "Адрес доставки", "Почта:". Затем модуль оплаты должен передать эти данные в Яндекс. Но не делает этого. В итоге email-уведомление об оплате от ЯндексДенег, в котором поля: "Ф.И.О.", "Адрес доставки", "E-mail": незаполнены.

2. Заказы попадают в статус "Пропавшие заказы". 
Несмотря на то, что в настройках модуля (в меню extension - feeds).
опция "Выберите статус заказа" установлена как "В обработке".

3. Не приходят письма оповещения о заказе. Ни клиенту, ни администратору!
Это существенный недостаток!
Причем, если используем другой модуль оплаты (например дефолтный "Оплата при доставке")
то все ок - письма приходят.
Возможно это связано с тем, что ваш модуль перенаправляет покупателя на сайт Яндекса,
а модуль "Оплата при доставке" завершается страницей "Ваш заказ сформирован!" ( index.php?route=checkout/success )

**Comment by ded100let** [comment]
1. Скоро доработаю, но это не всегда нужно.
2 если заказ оформлен и оплачен, он принимает нужный статус..
3. если заказ оформлен и оплачен он отправляет на нужную страницу. но это не связано с письмами.. Проверяйте спам.

**Comment by mak200** [comment]
3. в спаме пусто, уведомления не отправляются модулем

**Comment by ded100let** [comment]
Уведомления отправляет магазин.

**Comment by mak200** [comment]
Хорошо, магазин.
Но тогда, почему он отправляет их при использовании дефолтного модуля "Оплата при доставке", но не делает этого при использовании этого модуля?

**Comment by ded100let** [comment]
Касса или p2p используешь?

**Comment by mak200** [comment]
Касса.

**Comment by mak200** [comment]
Причина может быть том, что в  Яндексе некорретно указан адрес магазина?
http://livreklama.ru/ вместо http://livreklama.ru/store/

**Comment by ded100let** [comment]
да. Возможно можно только в корне домена. поэтому и не проходит. Уточните в поддержке. Если не в этом дело отправите на почту ftp и админку, я проверю

**Comment by ded100let** [comment]
Не могу сейчас демо показать, ssl истёк. но письма идут 100%. их шлёт сам opencart при формировании заказа.

**Comment by mak200** [comment]
дадите почту свою?

**Comment by ded100let** [comment]
esyara1@ya.ru. смогу посмотреть только завтра.

**Comment by mak200** [comment]
Отправил, спасибо за участие.

**Comment by mak200** [comment]
Поддержка ответила.
Магазин подключен на email схему в которой отправка check & aviso не предусмотрена.

**Comment by mak200** [comment]
Все эти проблемы повторились и при http схеме уведомления.
Причем, что интересно, в тестовом режиме заказы получают правильный статус и нормально приходят оповещения.

**Comment by mak200** [comment]
Также обнаружена ошибка.
Некорректный формат параметра "CustomerNumber" — строка, не должна превышать по длине 64 символа.

Решается заменой 29-й строки в:
https://github.com/yandex-money/yandex-money-cms-opencart2/blob/master/yandex_pack_opencart/catalog/controller/payment/yamodule.php

$data['customerNumber'] = $order_info['payment_firstname'] . ' ' . $order_info['payment_address_1'] . ' ' . $order_info['payment_address_2'] . ' ' . $order_info['payment_city'] . ' ' . $order_info['email'];
 
на
$data['customerNumber'] = $order_info['email'];

**Comment by ded100let** [comment]
спасибо мы учтём.

**Comment by ikarmanov** [comment]
Добрый день.

Ваша проблемы еще актуальны?

**Comment by mak200** [comment]
Эти вопросы удалось решить перейдя c email на http схему подключения.
Однако, думаю, что они по прежнему актуальны для email схемы подключения.
Подробней о схемах подключения здесь (п.1.2) https://money.yandex.ru/doc.xml?id=527069
