### ISSUE TITLE
Доступ запрещен!

### ISSUE THREAD

**Issue by kerr** [yandex-money/yandex-money-cms-opencart2#23]
OpenCart 2 (2.0.3.0)
после установки пишет..
Доступ запрещен!
У Вас нет прав для доступа к этой странице. Если она Вам нужна, обратитесь к администратору.

**Comment by ded100let** [comment]
Куда именно запрещён доступ?

**Comment by kerr** [comment]
Модули > Оплата > "Редактирование" Яндекс деньги дополнение

**Comment by kerr** [comment]
настройки случайно нашел в
Каналы продвижения > Y.CMS OpenCart 2

**Comment by ded100let** [comment]
Читайте инструкции! Там написано где настройки.
Модуль оплаты трогать ненужно. всё там.

**Comment by kerr** [comment]
нашел единственную инструкцию по ссылке https://github.com/yandex-money/yandex-money-cms-opencart2/blob/master/HOWTO-INSTALL.md

подскажите мне пожалуйста где еще почитать про данный модуль

**Comment by ded100let** [comment]
Извините я ошибся, перепутал с другой cms, обязательно исправим, если есть ещё какие-то вопросы - обязательно пишите.

**Comment by kerr** [comment]
а есть какое нибудь быстрое решение? я только вчера начал изучать OpenCart2..
и моя ошибка подтвердилась?

**Comment by ded100let** [comment]
какая ошибка? с доступом? там и не должно быть настроек.
Только Каналы продвижения > Y.CMS OpenCart 2

**Comment by kerr** [comment]
т.е. все так как и должно быть?

**Comment by ded100let** [comment]
я же вам написал, да. Все настройки там.

**Comment by kerr** [comment]
спасибо

**Comment by Tmin10** [comment]
Настройки есть и на странице оплаты, если предварительно включить модуль в каналах продвижения.

**Comment by zhenya2501** [comment]
привет. Мо
![2jnglupmv7g](https://cloud.githubusercontent.com/assets/19607612/15605651/f4e4b050-240f-11e6-9150-d6089fc4ae26.jpg)
![f2h5fyyv6wg](https://cloud.githubusercontent.com/assets/19607612/15605653/f4e90d12-240f-11e6-99cd-c42a36d13e12.jpg)
![nx0fgkkg5xi](https://cloud.githubusercontent.com/assets/19607612/15605654/f4e93dbe-240f-11e6-9f4a-1fa3b5c0280c.jpg)
![zvf_44w_6hy](https://cloud.githubusercontent.com/assets/19607612/15605652/f4e8a818-240f-11e6-9c53-3456ed2be56e.jpg)



жет кто сталкивался или знает, как решить это.
Стоит - ocStore 2.1.x, шаблон и оформление заказа - по умолчанию (не сторонние модули). Ставлю Яндекс.Касса версии 1.7.0.3, последнюю на данный момент. При оформлении заказа (на скриншотах указал проблему), когда выбираю - Способ оплаты - Яндекс.Касса - снизу не всплывают, не появляются способы оплаты. В админке стоят все способы. 
Спасибо.
