### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by malike-rnd** [yandex-money/yandex-money-cms-opencart2#24]
Ошибка в админке
https://hsto.org/files/422/edc/08c/422edc08c1874af6b1576f75e0fd2769.png
и в самом xml
http://new.pcshop.su/index.php?route=feed/yamarket 

P.S. Версия 2.0.2.0

**Comment by malike-rnd** [comment]
В админке ошибка сама пропала, а вот в xml нет. мистика :)

**Comment by ded100let** [comment]
Здравствуйте. чистый opencart? для проверки потребуется ftp и админка. На почту конечно

**Comment by malike-rnd** [comment]
Здравствуйте, спасибо за отклик! Где вашу почту взять?)

**Comment by ded100let** [comment]
2343319@gmail.com

**Comment by malike-rnd** [comment]
Отправил.

**Comment by chalipasha** [comment]
Скажите, в чем может быть проблема выгружаются только категории http://zip161.ru/index.php?route=feed/yamarket opencart 2.0.3

**Comment by ikarmanov** [comment]
Добрый день.

Проблема еще актуальна?

**Comment by malike-rnd** [comment]
Добрый, проблема не актуальна.
