### ISSUE TITLE
Выгружаются только категории opencart 2.0.3

### ISSUE THREAD

**Issue by chalipasha** [yandex-money/yandex-money-cms-opencart2#25]
Скажите, в чем может быть проблема выгружаются только категории http://zip161.ru/index.php?route=feed/yamarket opencart 2.0.3

**Comment by ded100let** [comment]
У вас выбрано выгружать из всех категорий?

**Comment by chalipasha** [comment]
http://prntscr.com/7h86pd, http://prntscr.com/7h86xe - сейчас из выбранных категорий. Когда ставишь галочку все категории и убираешь галки со всех категорий то выбивает ошибку http://prntscr.com/7h87hz

**Comment by ded100let** [comment]
напишите ftp и админку на esyara1@ya.ru я посмотрю.

**Comment by chalipasha** [comment]
Нужно чтобы не выводилось 
Здравствуйте! Как убрать   ( type =" vendor.model ") из шапки  <offer   id =" 2 "   available =" true "   type =" vendor.model " >
Нужно чтобы выводилось без производителя
\catalog\controller\feed\yamarket.php - это файл отвечает за формирования ее?

Удаляю эти две строчки, производитель не выгружает но яндекс маркет ругается так как в шапке offer есть type =" vendor.model "
$data['vendor'] = $product['manufacturer'];
$data['vendorCode'] = $product['model'];

Вообщем нужен вывод такого типа. взята с другого сайта. яндекс маркет принимает такое 

<offer id="4303" available="true">
<url>
http://magazin.skvis.ru/111/111/katalog/zapchasti/zapchasti-dlya-stiralnykh-mashin/salnik/salnik-25x47x10-gp-s-2000084-slb056un-detail
</url>
<price>280</price>
<currencyId>RUB</currencyId>
<categoryId>66</categoryId>
<picture>
http://magazin.skvis.ru/111/images/stories/virtuemart/product/SLB014.jpg
</picture>
<delivery>true</delivery>
<name>Сальник 25x47x10 GP с 2000084, SLB056UN</name>
</offer>

**Comment by chalipasha** [comment]
Разобрался, это Упрощённый yml ?


Среда, 24 июня 2015, 12:54 +03:00 от Павел Чалый <chali_pasha@mail.ru>:
>Нужно чтобы не выводилось 
>Здравствуйте! Как убрать   ( type =" vendor.model ") из шапки  <offer   id =" 2 "   available =" true "   type =" vendor.model " >
>Нужно чтобы выводилось без производителя
>\catalog\controller\feed\yamarket.php - это файл отвечает за формирования ее?
>
>Удаляю эти две строчки, производитель не выгружает но яндекс маркет ругается так как в шапке offer есть type =" vendor.model "
>$data['vendor'] = $product['manufacturer'];
>$data['vendorCode'] = $product['model'];
>
>Вообщем нужен вывод такого типа. взята с другого сайта. яндекс маркет принимает такое 
>
><offer id="4303" available="true">
><url>
>http://magazin.skvis.ru/111/111/katalog/zapchasti/zapchasti-dlya-stiralnykh-mashin/salnik/salnik-25x47x10-gp-s-2000084-slb056un-detail
></url>
><price>280</price>
><currencyId>RUB</currencyId>
><categoryId>66</categoryId>
><picture>
>http://magazin.skvis.ru/111/images/stories/virtuemart/product/SLB014.jpg
></picture>
><delivery>true</delivery>
><name>Сальник 25x47x10 GP с 2000084, SLB056UN</name>
></offer>



**Comment by chalipasha** [comment]
И еще вопрос как сделать available="true" и available="false"
Ставлю в настройках Доступность:  Доступны если > 0, остальные на заказ  Выдает  available="true" 
Пробовал все на заказ все равно  available="true" 

доступ к админки 
demo
demo

ftp zip161.ru
demo 
demo12345

Среда, 24 июня 2015, 13:04 +03:00 от Павел Чалый <chali_pasha@mail.ru>:
>Разобрался, это Упрощённый yml ?
>
>
>Среда, 24 июня 2015, 12:54 +03:00 от Павел Чалый <chali_pasha@mail.ru>:
>>Нужно чтобы не выводилось 
>>Здравствуйте! Как убрать   ( type =" vendor.model ") из шапки  <offer   id =" 2 "   available =" true "   type =" vendor.model " >
>>Нужно чтобы выводилось без производителя
>>\catalog\controller\feed\yamarket.php - это файл отвечает за формирования ее?
>>
>>Удаляю эти две строчки, производитель не выгружает но яндекс маркет ругается так как в шапке offer есть type =" vendor.model "
>>$data['vendor'] = $product['manufacturer'];
>>$data['vendorCode'] = $product['model'];
>>
>>Вообщем нужен вывод такого типа. взята с другого сайта. яндекс маркет принимает такое 
>>
>><offer id="4303" available="true">
>><url>
>>http://magazin.skvis.ru/111/111/katalog/zapchasti/zapchasti-dlya-stiralnykh-mashin/salnik/salnik-25x47x10-gp-s-2000084-slb056un-detail
>></url>
>><price>280</price>
>><currencyId>RUB</currencyId>
>><categoryId>66</categoryId>
>><picture>
>>http://magazin.skvis.ru/111/images/stories/virtuemart/product/SLB014.jpg
>></picture>
>><delivery>true</delivery>
>><name>Сальник 25x47x10 GP с 2000084, SLB056UN</name>
>></offer>
>
>




**Comment by KonstantinDK** [comment]
проверил на 2.0 опенкарте, Скоро будет обновление модуля. На это нужно время

**Comment by ded100let** [comment]
проверил на 2.0 опенкарте, Скоро будет обновление модуля. На это нужно время

**Comment by chalipasha** [comment]
Здравствуйте! скажите как сделать, чтобы заказы приходили без оплаты. То есть в 2 этапа, сначала человек оформляет заказ и переходит к оплате (в заказах должно отобразиться заказ со статусом в обработке). А потом как человек оплатил статус меняется на другой "Оплачен"

**Comment by ikarmanov** [comment]
chalipasha, добрый день.

Ваш вопрос еще актуален?

**Comment by chalipasha** [comment]
Да.

**Comment by ikarmanov** [comment]
Добрый день.

Рекомендую написать на cms@yamoney.ru, если Ваш вопрос актуален.
