### ISSUE TITLE
Яндекс.Касса callback

### ISSUE THREAD

**Issue by myxrome** [yandex-money/yandex-money-cms-opencart2#26]
Настройки Яндекс.Касса по умолчанию выставлять url для callback: index.php?route=payment/yandexmoney/callback.
Файл контроллера в модуле называется yamodule.php (контроллер соответственно ControllerPaymentYamodule), что приводит к ошибке 404 при формировании платежа на установках по умолчанию.

Переименуйте, пожалуйста, файл и контроллер или измените установки по умолчанию в настройках пользователя Яндекс.Касса.

**Comment by ikarmanov** [comment]
Добрый день.

Вы указали адрес платежного модуля для CMS Opencart 1.5. Для CMS Opencart необходимо выбирать пункт `Y.CMS (Opencart 2)`.
![lk-y cms-opencart](https://cloud.githubusercontent.com/assets/5497216/9441735/82680db0-4a80-11e5-9621-9788cda249d5.png)
