### ISSUE TITLE
Не корректное отображение html классов

### ISSUE THREAD

**Issue by lyolic** [yandex-money/yandex-money-cms-opencart2#29]
В ряде тем, например, в популярной теме Journal,  Метод оплаты(Оплата из кошелька в Яндекс.Деньгах.	Оплата с банковской карты.), в случае включения опции QuickCheckout,  не корректно отображается - его не видно!, и приходится ручками химичить с атрибутами lass="highlight" и class="button", для того чтобы методы оплаты стали видны.
С пейпалом, например, такой проблемы нет.

**Comment by ikarmanov** [comment]
Добрый день.

Проблема еще актуальна?
