### ISSUE TITLE
нет номера заказа

### ISSUE THREAD

**Issue by mak200** [yandex-money/yandex-money-cms-opencart2#30]
Не знаете ли, почему в письме уведомлении о платеже от Яндекса нет номера заказа из интернет магазина?
Как идентифицировать за какой заказ пришла оплата?
Эта информация вообще передается платежным модулем?

**Comment by ikarmanov** [comment]
Добрый день.

Номер заказа передается в поле orderNumber платежной формы для сервиса Яндекс.Касса. Если я правильно понял Ваш вопрос, то Вы можете попросить менеджера Яндекс.Кассы включить данное поле в состав реестра

**Comment by mak200** [comment]
Вопрос решен менеджерами Яндекс.Кассы.
