### ISSUE TITLE
Формируемый xml для Яндекс.Маркет не проходит проверку в Яндекс маркете

### ISSUE THREAD

**Issue by vicgor** [yandex-money/yandex-money-cms-opencart2#31]
Формируемый xml для Яндекс.Маркет не проходит проверку в Яндекс маркете.
```xml
<url>http://www.7tis.ru/index.php?route=product/product&amp;product_id=50</url>
```

>Выявлены нарушения Требований к рекламным материалам:
>-Страница товарного предложения не открывается

Как понимаю проблема в `&amp;`

Как решить эту проблему?

**Comment by ikarmanov** [comment]
Добрый день.

Необходимо изменить [строку файла модуля](https://github.com/yandex-money/yandex-money-cms-opencart2/blob/master/src/upload/catalog/controller/feed/yamarket.php#L81) заменив 
```
$data['url'] = str_replace('https://', 'http://', $this->url->link('product/product', 'product_id=' . $product['product_id']));
```
на 
```
$data['url'] = str_replace('https://', 'http://', htmlspecialchars_decode($this->url->link('product/product', 'product_id=' . $product['product_id'])));
```
В новой версии модуля это исправим. Спасибо.

**Comment by vicgor** [comment]
Есть еще одна проблема с xml. Нужна возможность задания текста по умолчанию для тега <sales_notes>
У меня в магазине 100% предоплата по пластиковым картам.
Служба проверки Яндекс маркет зачем-то требует это указать в этом теге.
Хотя это и так очевидно если оплата производится пластиковой картой.

**Comment by ikarmanov** [comment]
Спасибо за информацию. 
Проверим и учтем это в следующих версиях модуля.
