### ISSUE TITLE
Не работает метрика

### ISSUE THREAD

**Issue by partizzzzzan** [yandex-money/yandex-money-cms-opencart2#34]
Сделал все по инструкции, в метрики выводится - счетчик не обнаружен, данные не поступают.

**Comment by neccospb** [comment]
+1

**Comment by ikarmanov** [comment]
Добрый день. 

Вы обновляли [файл модификатора Y.CMS](https://github.com/yandex-money/yandex-money-cms-opencart2/raw/master/ycms.1.0.1.ocmod.xml) до версии 1.0.1?

**Comment by partizzzzzan** [comment]
Да! не работает

**Comment by Zanimo** [comment]
не работает!
метрика подключилась после внесения кода в header
