### ISSUE TITLE
Атрибут sales_notes для Я.Маркет

### ISSUE THREAD

**Issue by Gop-Stop** [yandex-money/yandex-money-cms-opencart2#35]
В Я.Маркете обязательный для выгрузки атрибут sales_notes (информация по предоплате) отсутствует в настройках, без него магазин не принимают(при условии работы по предоплате).

> Доставка товара осуществляется только после 100% предоплаты. Обратите внимание, информацию о том, что Вы работаете только на условиях предоплаты, необходимо указать в прайс-листе, в теге sales_notes

**Comment by ikarmanov** [comment]
Добрый день.

До внесения изменений в модуль значение для этого параметра можно установить через добавление строки `$data['sales_notes'] = 'нужный_текст'` в файл после [строки 95](https://github.com/yandex-money/yandex-money-cms-opencart2/blob/6e3667c0cd0b7964ee4591b8179ce4497c7e0d41/src/upload/catalog/controller/feed/yamarket.php#L95).

**Comment by Gop-Stop** [comment]
Нужно поле для ввода информации в этот параметр. До 50 символов.
