### ISSUE TITLE
Проблемы с установкой

### ISSUE THREAD

**Issue by Anastasy-ya** [yandex-money/yandex-money-cms-opencart2#38]
Здравствуйте. Не получается установить модуль. Пытаюсь поставить приложение на Opencart 2.1.0.2 сборка ocstore. Делаю всё по инструкции: загружаю в магазин через стандартный установщик расширений файл ycms.ocmod.xml,обновляю через менеджер дополнений,  далее захожу в каналы продвижения,а там нет «Y.CMS от яндекс кассы»
Помогите пожалуйста.

**Comment by ikarmanov** [comment]
Добрый день.

Проблема может возникать из-за отсутствия настроек FTP для установщика расширений. Вам необходимо в этом убедиться.
Можно установить модуль вручную, но перед этим нужно удалить элемент 'Y.CMS' из раздела 'Установщик расширений - Модификаторы', чтобы исключить возможные конфликты.

***Установка модуля вручную***
1. Распаковать архив с модулем во временный каталог и загрузить содержимое каталога `upload` в корень сайта (там где есть каталоги `admin`, `catalog`, `system`);
2. Удалить содержимое каталога `upload` из временного каталога и упаковать остальные файлы и каталог `upload` в `ycms.manual.ocmod.zip`. Т.е. должен получиться архив, который отличается от нашего только пустым каталогом `upload`;
3. Установить обновленный архив через установщик расширений.
