### ISSUE TITLE
Курс валюты в прайс-листе на 30% отличается от курса национального банка

### ISSUE THREAD

**Issue by bolahg** [yandex-money/yandex-money-cms-opencart2#39]
Приветствую. Ранее все было норм. 
И тут получил с ямаркета следующее сообщение:

> Размещение Вашего магазина  было приостановлено за повторяющиеся ошибки в прайс-листе.
> Ошибки при разборе файла:
> Дата из файла: 2016-02-09 01:47 (строка 1, столбец 116)
> Фатальная ошибка: Курс валюты (0.856384) в прайс-листе на 30% отличается от курса национального банка (85.6543). (строка 10, столбец 14)
> Фатальная ошибка: Фид отклонен (строка 10, столбец 14)

В магазине курсы валют установлены относительно рубля (рубль 1.0000).
При экспорте стоит галка экспортировать все валюты.
Как исправить данную ситуевину?

**Comment by ikarmanov** [comment]
Добрый день.

Какие значения у других валют?

**Comment by bolahg** [comment]
![2016-02-11 20-45-28](https://cloud.githubusercontent.com/assets/9381510/12979321/895449e8-d100-11e5-8c7e-ee909f04c12e.png)
