### ISSUE TITLE
Не отображаются заказы в админ. панели

### ISSUE THREAD

**Issue by Criotin** [yandex-money/yandex-money-cms-opencart2#40]
Здравствуйте уважаемые разработчики.

Проблема заключается в том, что никаких признаков о совершенной покупке в админ. панели не отображается. Сама купля-продажа товара происходит нормально.

Использую для приема платежей Яндекс.Деньги.

Помогите пожалуйста разобраться с проблемой.

**Comment by ikarmanov** [comment]
Добрый день.

Прошу Вас прислать снимок экрана с настройками модуля и описанием проблемы на адрес `cms@yamoney.ru`.

**Comment by Criotin** [comment]
Уже месяц жду и никакой помощи.
Господа - АУУУ, помогите пожалуйста с проблемой.

**Comment by ikarmanov** [comment]
Добрый день.

Если проблема актуальна, то прошу Вас установить актуальную версию модуля, настроить его работу по [инструкции](https://kassa.yandex.ru/files/manual_y.cms_opencart2.pdf). Если проблема осталась, то напишите на cms@yamoney.ru
