### ISSUE TITLE
Не работает тег oldprice для Я.Маркета

### ISSUE THREAD

**Issue by Gop-Stop** [yandex-money/yandex-money-cms-opencart2#41]
Добрый день! Не работает тег <oldprice> для Я.Маркета. Выгружается цена со скидкой, но не высчитывается % скидки, т.к не передается старая цена.

> oldprice
> Старая цена на товар, которая обязательно должна быть выше новой цены (<price>). Параметр <oldprice> необходим для автоматического расчета скидки на товар.

**Comment by ikarmanov** [comment]
Добрый день.

Занимаемся проверкой.

**Comment by andre2git** [comment]
у себя делал так 

в [строке 31](https://github.com/yandex-money/yandex-money-cms-opencart2/blob/master/src/upload/catalog/model/yamodel/yamarket.php#L31) заменяем `IFNULL(ps.price, p.price) AS price` на `p.price AS price` 
а [строку 180](https://github.com/yandex-money/yandex-money-cms-opencart2/blob/master/src/upload/catalog/model/yamodel/yamarket.php#L31) приводим к виду `$allowed = array('url', 'price', 'oldprice', 'currencyId', 'categoryId', 'picture', 'store', 'pickup', 'delivery', 'name', 'vendor', 'vendorCode', 'model', 'description', 'sales_notes', 'downloadable', 'weight', 'dimensions', 'param', 'sales_notes', 'country_of_origin');`

добавить после [строки 84](https://github.com/yandex-money/yandex-money-cms-opencart2/blob/master/src/upload/catalog/controller/feed/yamarket.php#L84) код `if ($product['special'] && $product['special'] < $product['price']) $data['oldprice'] = $product['price'];`

**Comment by sh2rman** [comment]
Работает! Только поправлю, что строку 180 надо искать в controller/feed
и еще маленькая правка: в Беларуси теперь валюта BYN называется

**Comment by ikarmanov** [comment]
Спасибо.
Готовим обновление по feedback'у с Github. Валюту и oldprice учтем.

**Comment by sh2rman** [comment]
Желательно добавить проверку величины получаемой скидки. Валидатор прайсов маркета ругается,  если она меньше 5%.

**Comment by ikarmanov** [comment]
**andre2git**, спасибо. Включили ваше предложение в новую версию модуля.
