### ISSUE TITLE
url продукта при выгрузке на маркет, вместо https http

### ISSUE THREAD

**Issue by andre2git** [yandex-money/yandex-money-cms-opencart2#42]
Для чего заменяется протокол https на http в url продуктов выгружаемых на маркет? 
Строка 81 в [файле](https://github.com/yandex-money/yandex-money-cms-opencart2/blob/master/src/upload/catalog/controller/feed/yamarket.php)

**Comment by ikarmanov** [comment]
Спасибо. Исправлено.
