### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Petriknet** [yandex-money/yandex-money-cms-opencart2#43]
Вылетает ошибка 2016-03-02 20:33:15 - PHP Notice:  Undefined index: type_data in rumanchester.ru/admin/controller/feed/yamodule.php on line 226. При это меняю данные в модуле я.маркет на упрощенный прайс или стоимость доставки в регионе. Нажимаю сохранить но не сохраняет.
Следующий вопрос:
У меня в продаже постельное белье с размерами 1,5 спальное, 2,0 спальное, евроразмер и т. д. Размер указываю в опции. Дело в том, что стоимость разная у каждого размера и цену на каждуй размер я указываю в опции с использованием модификатора, т. е. 1,5 размер 1500р.
А модуль Y.CMS для каждого размера делает свое товарное предложение хотя товар один и тот же и URL тоже (яндекс маркет не пропустит). А первоначальная цена у меня выбирается по цене малого размера. Во время попытки прохождения проверки, когда человек переходит с товарного предложения 2,0 спального постельного белья на мой ИМ, то видит цену 1,5 спального  это также не пропускает яндекс маркет. А плодить копии одного товара не вижу смысла (типа разделить на категории по размерам)

**Comment by ikarmanov** [comment]
Спасибо. 

> PHP Notice: Undefined index: type_data

 Ошибка исправлена

**Comment by Petriknet** [comment]
Здравствуйте. Обновил модуль до 1,6 и при создании yml-файла выдает следующие ошибки: Fatal error: Uncaught exception 'Exception' with message 'Need set decimal places for RUB' in /var/www/petriknet/data/www/rumanchester.ru/catalog/controller/feed/yamarket.php:30 Stack trace: #0 [internal function]: ControllerFeedYamarket->index(Array) #1 /var/www/petriknet/data/www/rumanchester.ru/system/modification/system/engine/action.php(65): call_user_func(Array, Array) #2 /var/www/petriknet/data/www/rumanchester.ru/system/engine/front.php(34): Action->execute(Object(Registry)) #3 /var/www/petriknet/data/www/rumanchester.ru/system/engine/front.php(29): Front->execute(Object(Action)) #4 /var/www/petriknet/data/www/rumanchester.ru/index.php(265): Front->dispatch(Object(Action), Object(Action)) #5 {main} thrown in /var/www/petriknet/data/www/rumanchester.ru/catalog/controller/feed/yamarket.php on line 3029.05.2016, 22:48, "ikarmanov" <notifications@github.com>:Спасибо. 


PHP Notice: Undefined index: type_data


Ошибка исправлена
