### ISSUE TITLE
При сбое оплаты меняется номер заказа

### ISSUE THREAD

**Issue by noobsaibot88** [yandex-money/yandex-money-cms-opencart2#44]
Т.е. если оплата не удалась, заказ оформляется с новым номером.
Эксклюзивный функционал)
Если у клиента произойдёт ошибка при оплате, и он от великого ума воспроизведёт её 100 раз, то получит 100 писем и 100 sms о новом заказе)

**Comment by ikarmanov** [comment]
Добрый день.

Рекомендую написать на cms@yamoney.ru, если Ваш вопрос актуален.
