### ISSUE TITLE
Отложенная оплата

### ISSUE THREAD

**Issue by noobsaibot88** [yandex-money/yandex-money-cms-opencart2#45]
Вы планируете внедрять это?

**Comment by ikarmanov** [comment]
Добрый день.

Отложенная оплата есть в долгосрочных планах, но точные сроки её реализации пока сказать затрудняюсь. 
Нам интересен Ваш взгляд на реализацию данного функционала. Например, Вы хотели бы всегда принимать отложенные платежи по картам или давать вашим плательщикам выбор между обычной оплатой по карте и отложенной?

**Comment by noobsaibot88** [comment]
На мой взгляд, лучше всего было бы засунуть окмодом ссылку на оплату прямо в локаль письма. Вида "Если вы ещё не оплатили, то "жмак". Таким образом, клиент ее или оплатит или увидит, что уже оплатил. Лучше, чем ничего. Ну и функционал не потреяется, если в роли респондера используется стороннее решение.

**Comment by ostulov** [comment]
Добрый день!

Развитие данного модуля приостановлено.
Функционал отложенной оплаты уже реализован в новом модуле для Opencart2 - https://github.com/yandex-money/yandex-money-ycms-v2-opencart
При переходе на новый модуль потребуется смена настроек на стороне Яндекс.Кассы. Это можно сделать через персонального менеджера.
