### ISSUE TITLE
Порядок сортировки

### ISSUE THREAD

**Issue by shom4ik** [yandex-money/yandex-money-cms-opencart2#46]
Добрый день, как сделать чтобы модуль оплаты яндекс деньгами стоял после "оплата при получении"??? сколько рыл так и не смог выставить порядок сортировки

**Comment by neccospb** [comment]
+1

**Comment by daosin** [comment]
+100

2016-04-18 12:57 GMT+03:00 neccospb <notifications@github.com>:

**Comment by noobsaibot88** [comment]
никак. про неё забыли.
если хотите быстро, то в модель допишите 'sort_order' => число какое надо

**Comment by ikarmanov** [comment]
Спасибо за информацию.
Учтем при выходе новой версии модуля.

**Comment by ikarmanov** [comment]
На данный момент порядок сортировки устанавливается во вкладке Яндекс.Касса и действует для режима пополнения кошелька.
