### ISSUE TITLE
Выгружаются только категории

### ISSUE THREAD

**Issue by shom4ik** [yandex-money/yandex-money-cms-opencart2#47]
Вообщем выгрузка в файл идет без товаров... 
как решить эту проблему?

**Comment by dolbayoga** [comment]
столкнулся с похожей проблемой. Все решилось указанием в товарах производителя.

**Comment by yuriygr** [comment]
Все проще. В файле
`catalog/controller/feed/yamarket.php`
Надо найти строку
`$products = $this->model_yamodel_yamarket->getProducts($ids_cat, true);`
И заменить **true** на **false**

**Comment by ikarmanov** [comment]
Спасибо за информацию.
Учтем отсутствие производителя товара или добавим в интерфейс настроек данную опцию.

**Comment by ikarmanov** [comment]
В код модуля добавили проверку кол-ва товаров и если они равны 0, то выгружаем повторно, но уже без учета производителя.
