### ISSUE TITLE
4к+ товаров не загружаются в маркет

### ISSUE THREAD

**Issue by bolahg** [yandex-money/yandex-money-cms-opencart2#49]
Добрый день.
Модуль версии 1.3. установлен
В маркет перестали загружаться товары. Пробовал упращенную версию ничего не изменилось.
До этого было 1к товаров, все было норм.
Теперь 4к+ товаров и они не загружаются. Прошу помочь. 
Пытался обновить модуль, но у меня вышло. Написано "Внимание! Пакет ycms_update.ocmod.zip предназначен для обновления модуля с версии 1.3.х" - такого файла я найти не смог. Пытался мастер загрузить, но опенкарт чего ругается про айди. Так что я не разобрался че делать. прикладываю сообщение с маркете при попытке загрузить товары. 
![2016-04-05_00-29-50](https://cloud.githubusercontent.com/assets/9381510/14258781/d0b7e3c8-fac5-11e5-8715-f594295915ce.png)

**Comment by ded100let** [comment]
Не хватает времени обработать файл. нужно увеличить параметр php max_execution_time

**Comment by iMateo** [comment]
Не уверен, что не хватает времени, т.к. у server timeout 504 ошибка, а тут 500 (internal error). Попробуйте увеличить доступную скрипту оперативную память через memory_limit

**Comment by ded100let** [comment]
Я уверен. Исправьте конфиг

**Comment by bolahg** [comment]
Исключил кривые категории
Переключился на упрощенный режим.
Умл стал загружаться. Отправил его на маркет. И теперь новые обшибки, не критичные но все же
Вместо нормального урл картинки генерируется вот такого типа:
http%3A%2F%2Fpumpland.ru%2Fimage%2Fcache%2Fcatalog%2Fproduct%2Fwilo%2Fstar-rs25-2-s-gajkami-4-600x600.jpg
>php max_execution_time 
какое нормальное значение?

**Comment by bolahg** [comment]
Поменял max_execution_time на 60 в обычном все равно не грузится.
Может ли быть проблема в том что страницы производителей не заполнены.

**Comment by bolahg** [comment]
Вам обоим по плюсу. 
Добавив таймаут на пхп и никсе - умл грузился через раз
Добавил выделяемой памяти с 128 на 256 - стало все грузится, сайт мап тоже.
А вот эти ошибки после обновления не проходят:

> Дата из файла: 2016-04-05 06:28 (строка 1, столбец 116)
> scheme: local_delivery_cost (строка 101, столбец 8)
> Предупреждение: Некорректный URL адрес картинки предложения: http%3A%2F%2Fpumpland.ru%2Fimage%2Fcache%2Fcatalog%2Fproduct%2Fwilo%2Fstar-rs25-2-s-gajkami-4-600x600.jpg (строка 280, столбец 9)
> Предупреждение: Некорректный URL адрес картинки предложения: http%3A%2F%2Fpumpland.ru%2Fimage%2Fcache%2Fcatalog%2Fproduct%2Fwilo%2Fstar-rs25-2-s-gajkami-2-600x600.jpg (строка 280, столбец 9)

**Comment by ded100let** [comment]
На сколько я вижу это валидный urlencode, всё должно пройти. Что показывает валидатор?
https://webmaster.yandex.ru/xsdtest.xml
Выберите "Маркет"

**Comment by bolahg** [comment]
Проверку По ссылке так и не дождался, загрузил файл хмл и вот что он выдал
![2016-04-05_15-10-57](https://cloud.githubusercontent.com/assets/9381510/14276417/a34c039e-fb40-11e5-9fcb-7af914f0c210.png)
Вот эти ссылки выгледят в самом хмл файле
![2016-04-05_15-13-43](https://cloud.githubusercontent.com/assets/9381510/14276549/1f73d62c-fb41-11e5-85c7-e48cecf6d0a8.png)

**Comment by Zanimo** [comment]
Поддерживаю, та же ошибка: прайс грузится, всё в порядке, фото-нет!

**Comment by ikarmanov** [comment]
В мае 2016 года внесены изменения, которые должны устранить проблему с ошибками в адресе продукта и его изображений. Они скоро будут включены в релиз, но уже сейчас можно загрузить новую версию файлов
