### ISSUE TITLE
Ссылка для приема сообщений выдает 404 ошибку

### ISSUE THREAD

**Issue by vicgor** [yandex-money/yandex-money-cms-opencart2#5]
Ссылка для приема сообщений выдает 404 ошибку
http://17i7.ru/index.php?route=payment/yamodule/inside

Какая правильная ссылка?

**Comment by ded100let** [comment]
Эти ссылки переписываются в запросе, попробуйте проверить оплату

**Comment by vicgor** [comment]
сделана заглушка
