### ISSUE TITLE
Модуль выдает ошибку в OpenCart 2.2

### ISSUE THREAD

**Issue by kembrick** [yandex-money/yandex-money-cms-opencart2#50]
В OpenCart 2.2 модуль Y.CMS версии 1.4.1 выдает ошибку при попытке оформления заказа Error: Could not load template /catalog/view/theme/default/template/default/template/payment/yamodule.tpl

**Comment by kembrick** [comment]
Лечится это следующим образом:
В файле /catalog/controller/payment/yamodule.php в строках 47-50 произвести такие изменения
`if (file_exists(DIR_TEMPLATE . $this->config->get('config_template') . 'payment/yamodule')) {
            return $this->load->view($this->config->get('config_template') . 'payment/yamodule', $data);
        } else {
            return $this->load->view('payment/yamodule', $data);`

К сожалению, как выяснилось, это не последняя проблема модуля.
При попытке отправки тестового платежа с банковской карты открывается пустая страница с адресом site.ru/index.php?route=payment/yamodule/yaredirect
Т.е. перехода на страницу Яндекс.Кассы не происходит. :(

**Comment by ikarmanov** [comment]
Добрый день.

Текущая версия модуля несовместима с CMS Opencart 2.2.x из-за изменений в его коде. Мы работаем над выпуском обновления (1.5.х), которое устранит проблемы совместимости. По срокам выхода сказать затрудняюсь.

**Comment by iMateo** [comment]
Здравствуйте, есть смысл вам помогать делать правки в коде для адаптации под 2.2 или вы не принимаете?

**Comment by AngryBeaver87** [comment]
@iMateo  Добрый день - можете подсказать как сделать чтоб Opencart 2.2. работала с текущей версией яндекс-кассы? Мне кажется я уже близок к этому, но все равно пока не работает.

**Comment by ikarmanov** [comment]
Модуль версии 1.5.0 совместим с Opencart 2.2.x
