### ISSUE TITLE
Выгрузка на Маркет

### ISSUE THREAD

**Issue by Zanimo** [yandex-money/yandex-money-cms-opencart2#52]
Здравствуйте,
столкнулся с ошибкой "Некорректный URL картинки предложения", в результате товар выгрузился на Маркет без картинок. Описал эту проблему по электронной почте, посоветовали загрузить актуальную версию модуля (1.4.2). Загрузил - в итоге Маркет не принимает прайс-лист вообще по причине "Ошибка спецификации XML"
[mist.txt](https://github.com/yandex-money/yandex-money-cms-opencart2/files/251418/mist.txt)
Использую ocStore 2.1.0.2. Жду рекомендаций, пока откатываюсь на предыдущую версию модуля.
И ещё: 
- sales_notes как делать? привязанного к нему поля нет в админке
- обязательный элементе model - тоже поля такого нет (хвала Яндексу, привязывает товар правильно и без этого параметра)
Метрика, кстати, тоже не работает, пришлось код в хэдер вносить.
Вот как-то так, не весело совсем, про Кассу даже думать боюсь...

**Comment by ikarmanov** [comment]
> столкнулся с ошибкой "Некорректный URL картинки предложения"
В мае 2016 года внесены изменения, которые должны устранить проблему с ошибками в адресе продукта. Они скоро будут включены в релиз, но уже сейчас можно загрузить новую версию файлов. 

> sales_notes как делать?
Думаем над реализацией.
