### ISSUE TITLE
Требуемая версия PHP 5.4 или 5.3

### ISSUE THREAD

**Issue by nanolan** [yandex-money/yandex-money-cms-opencart2#53]
В файле catalog/model/yamodel/yamarket.php используется ENT_XML1, а согласно Changelog, ENT_XML1 поддерживаетмся только с версии 5.4:

"5.4.0 - The constants ENT_HTML401, ENT_XML1, ENT_XHTML and ENT_HTML5 were added."

Значит версия phph 5.3 не подойдет?

**Comment by ikarmanov** [comment]
Спасибо. Учтем этот момент в новой версии модуля.
