### ISSUE TITLE
Оформление заказа при отказа от оплаты

### ISSUE THREAD

**Issue by yuriygr** [yandex-money/yandex-money-cms-opencart2#54]
Здравствуйте. Если человек выбрал метод оплаты через яндекс.деньги, то заказ сразу формируется, независимо, оплатил он или нет. Можно ли это как-то исправить?

**Comment by yuriygr** [comment]
Нашёл пока только такое решение:
В файле **catalog/controller/payment/yamodule.php** заккоментировать строку:
```
public function confirm(){
	if ($this->session->data['payment_method']['code'] == 'yamodule') {
		$this->load->model('checkout/order');
		//$this->model_checkout_order->addOrderHistory($this->session->data['order_id'], $this->config->get('config_order_status_id'), '', true);
	}
}
```

**Comment by ikarmanov** [comment]
Добрый день.

Вы верно определили строку кода, которая отвечает за изменения статуса заказа. Вопрос закрываю.
