### ISSUE TITLE
 Заказы на Маркете

### ISSUE THREAD

**Issue by r0d1n2** [yandex-money/yandex-money-cms-opencart2#55]
При включении  Заказы на Маркете в тестовых логах выходит такая ошибка, как быть, что делать?
URL = https://werthmann.ru/yandexbuy/cart
Параметры URL: auth-token=**<удалена_приватная_информация>**
Детали ошибки = 404 Not Found

**Comment by ikarmanov** [comment]
Добрый день.

> Детали ошибки = 404 Not Found
Вам необходимо проверить настройки ЧПУ вашего сайта или содержимое файла htaccess.

**Comment by r0d1n2** [comment]
Нашел ошибку в htaccess
теперь CANT_GET_RESPONSE
URL = https://werthmann.ru/yandexbuy/cart
Параметры URL: auth-token=
Детали ошибки = 302 Found

**Comment by r0d1n2** [comment]
Проблемы связана с seopro, при выключении seopro начинает работать

Как подружить с seopro

**Comment by devildozen18** [comment]
Решили проблему???? У меня также!

**Comment by r0d1n2** [comment]
К сожалению нет, тупо забил на это 😊



Отправлено из мобильной Почты Mail.Ru


Понедельник, 18 июля 2016 г., 23:17 +0500 от notifications@github.com  <notifications@github.com>:

**Comment by devildozen18** [comment]
плохо! в итоге написано: Программа «Заказ на Маркете»: приостановлена (ошибки качества)

**Comment by r0d1n2** [comment]
Замучил тех.поддержку яндекса, они дали ответ, что модуль сделан для чистого opencart, а seopro это дополнение и посоветовали теребить разработчиков seopro. А на github отвечают раз в год

**Comment by devildozen18** [comment]
это точно

**Comment by devildozen18** [comment]
как же все-таки решить данную проблему????? думаю она легко решается, если знать куда копать

**Comment by ikarmanov** [comment]
Подробности [тут](https://github.com/yandex-money/yandex-money-cms-opencart2/issues/101)
