### ISSUE TITLE
Как удалить старую версию и установить новую версию вручную

### ISSUE THREAD

**Issue by vicgor** [yandex-money/yandex-money-cms-opencart2#56]
Подскажить как вручную установить модуль.
И надо ли удалять старую версию?

**Comment by ikarmanov** [comment]
Добрый день.

Для удаления модуля вручную необходимо:

1. отключить модуль через меню административной панели;
2. отключить и удалить Y.CMS модификатор через меню административной панели;
3. удалить файлы модуля, которые были скопированы из каталога upload архива с модулем

>Внимание! Удалять необходимо только файлы модуля, а не каталоги. Удалив каталоги вы можете нарушить работоспособность сайта.

До выхода версии 2.х нашего модуля необходимость в удалении старых версий отсутствует.
