### ISSUE TITLE
Ошибка при выгрузке прайса в яндекс маркет

### ISSUE THREAD

**Issue by John788** [yandex-money/yandex-money-cms-opencart2#57]
Warning: implode() [function.implode]: Invalid arguments passed in /var/www/u0184932/data/www/.../new/catalog/controller/feed/yamarket.php on line 16
дальше идет куча кракозябр типа вот этого РРЅРєСѓР±Р°С‚РѕСЂС‹ РґР»СЏ СЏРёС† Р°РІС‚РѕРјР°С‚РёС‡РµСЃР
Версия модуль 1.4.1.1, версия Opencart 2.0.3.1

**Comment by John788** [comment]
Прошу прощения, закрываем - не выставил категории... С выставленными все работает.

**Comment by ikarmanov** [comment]
Спасибо за информацию. 
Добавим проверку выбора категорий, чтобы исключить отображение странных сообщений об ошибках.
