### ISSUE TITLE
как установить два модуля

### ISSUE THREAD

**Issue by motaby** [yandex-money/yandex-money-cms-opencart2#58]
Подскажите как установить два модуля yandex-money-cms-opencart2 на один магазин, для выгрузки двух прайсов с разными предложениями. спасибо

**Comment by ikarmanov** [comment]
Добрый день.

Использовать модуль для одновременной выгрузки прайс-листа с разными предложениями невозможно. Вы можете описать ситуацию, которая требует данного решения?
