### ISSUE TITLE
Проблема с сертификатом, отсутствием оплаты по данному заказу или указан ошибочный идентификатор магазина

### ISSUE THREAD

**Issue by neccospb** [yandex-money/yandex-money-cms-opencart2#59]
OC 2.1.0.2 + Y.CMS 1.4.2
При нажатии "управление заказом" на боевом заказе вываливается ошибка.
В настройках всё прописано, сертификат прикручен, тестовые платежи (на предыдущих версиях) проходили. С чем может быть связано? Куда копать? Где читать логи?
![katavas1](https://cloud.githubusercontent.com/assets/14109592/16089928/02746f28-3336-11e6-9fc6-6ccc4b684210.jpg)
![katavas](https://cloud.githubusercontent.com/assets/14109592/16089932/063f3a2a-3336-11e6-8c12-f2f4165be58e.jpg)
![katavas2](https://cloud.githubusercontent.com/assets/14109592/16089941/0b816292-3336-11e6-8174-93291ab1673f.jpg)

**Comment by aralex** [comment]
Имею аналогичную ошибку. Есть подозрение, что при генерации запроса на сертификат используются не совсем корректные данные.

**Comment by neccospb** [comment]
> Имею аналогичную ошибку (№1). Есть подозрение, что при генерации запроса на сертификат используются не совсем корректные данные.
какие пути решения предполагаете? или пока не мешает работать?

**Comment by aralex** [comment]
Работать мешает :) Будем изучать вопрос с инженерами техподдержки Яндекс.Кассы.
На самом деле проблема, видимо, сложнее. У меня MWS не заработал на сертификате, который мне сгенерили в Яндексе на основе закрытого ключа и запроса на сертификат, которые я создал сам по их инструкции. Те, что предложил модуль, в Яндексе забраковали. После того, как MWS не заработал, инженеры предложили мне попробовать на "родном" сертификате, который создан на основе закрытого ключа и запроса на сертификат, которые предложил модуль.
Сейчас вот ожидаю "родного" сертификата. Будем разбираться.
На самом деле, возможно, вам стоит самому дёрнуть техподдержку...

**Comment by ikarmanov** [comment]
> При нажатии "управление заказом" на боевом заказе вываливается ошибка 1.

Может быть у вашего сайта сменился IP, а на стороне Яндекс.Кассы указано другое значение. В настройках Кассы включен тестовый или реальный режим? 

>Те, что предложил модуль, в Яндексе забраковали.

Это исключительная ситуация. Вы можете написать на cms@yamoney.ru, указав данные магазина и предоставив временный доступ в административную панель сайта для анализа ситуации.

**Comment by neccospb** [comment]
Спасибо за обратную связь.
По **ошибке №1** получен ответ от yamoney_shop@yamoney.ru

> "Сам платеж в Ваш магазин завершается успешно.
> Функции, указанные на вкладке "Управление заказами", становятся доступными после отдельного подключения через менеджера. Соответственно сейчас возникает сообщение об этой ошибке." 
(пока жду ответ от менеджера)
**ошибка №2** ушла после отключения HTTPS в admin\config.php

**Comment by neccospb** [comment]
Сертификат MWS получен от Яндекса и успешно загружен через интерфейс модуля, но ошибка по-прежнему осталась "Проблема с сертификатом, отсутствием оплаты по данному заказу или указан ошибочный идентификатор магазина"..

**Comment by Alexmsk11** [comment]
Аналогичная проблема, проблема озвучена специалистам poisk@yamoney.ru, ответа нет

**Comment by ikarmanov** [comment]
Если проблема актуальна, то прошу Вас написать на cms@yamoney.ru. Наличие временного доступа к настройкам модуля и его файлам позволит сократить время на анализ и устранение проблемы.

**Comment by neccospb** [comment]
спасибо, проблема решена включением https и перевыпуском сертификата.
