### ISSUE TITLE
В оформлении заказа не появляются способы оплаты на ocStore 2.1.0.2.1, Я.Касса 1.7.0.3

### ISSUE THREAD

**Issue by zhenya2501** [yandex-money/yandex-money-cms-opencart2#60]
Здравствуйте.
Часто встречается такая проблема (где-то помогает смена шаблона или модуля упрощенного оформления заказа.
В общем в Способе оплаты при выборе - Яндекс.Касса - снизу не появляются способоы оплаты (например, банковская карта, Яндекс.Деньги  и т.д.)
Специально шаблон на движке оставил по умолчанию)
![2jnglupmv7g](https://cloud.githubusercontent.com/assets/19607612/15605803/dcbb6e82-2410-11e6-9cae-00f70a5b86d4.jpg)
![f2h5fyyv6wg](https://cloud.githubusercontent.com/assets/19607612/15605804/dcbb9880-2410-11e6-9caa-b15d6a1977b0.jpg)
![nx0fgkkg5xi](https://cloud.githubusercontent.com/assets/19607612/15605802/dcbb1b62-2410-11e6-9e29-8d1a4e4e5f2b.jpg)
![zvf_44w_6hy](https://cloud.githubusercontent.com/assets/19607612/15605805/dcbed748-2410-11e6-83cf-3ce5bbccdca1.jpg)

**Comment by ikarmanov** [comment]
Добрый день.

На данном шаге выбирается платежная система/сервис. Способы оплаты отображаются после перехода к следующему шагу оформления заказа. Можно совсем исключить выбор оплаты на стороне магазина в пользу выбора методов оплаты на стороне сервиса Яндекс.Касса.
