### ISSUE TITLE
Когда будет готова версия для OpenCart 2.2.0.0 ?

### ISSUE THREAD

**Issue by Alexmsk11** [yandex-money/yandex-money-cms-opencart2#64]
Представители компании Яндекс, скажите пожалуйста когда будет готова версия для OpenCart 2.2.0.0 ?

**Comment by ikarmanov** [comment]
Добрый день.

Версия от разработчика расположена в [1.5.0-dev](https://github.com/yandex-money/yandex-money-cms-opencart2/tree/1.5.0-dev) и сейчас мы тестируем новый функционал. Сегодня некоторые файлы будут обновлены. После тестов мы выпустим релиз 1.5.0 и опубликуем на основной странице модуля. 

По срокам:
- основной релиз будет опубликован до 30 июня 2016 года;
- тесты планируем завершить до 27 июня 2016 года;
- основные изменения в 1.5.0-dev будут опубликованы до 18 июня 2016 года
