### ISSUE TITLE
Y.CMS нет данных в Метрике

### ISSUE THREAD

**Issue by Alexmsk11** [yandex-money/yandex-money-cms-opencart2#65]
Не поступают данные в метрику со страниц магазина OpenCart 2.2.0.0

Y.CMS от Яндекс.Кассы (1.5.0)

все параметры настроены согласно инструкции

**Comment by ikarmanov** [comment]
Добрый день.

Рекомендую обновить [файл модификатора](https://github.com/yandex-money/yandex-money-cms-opencart2/raw/master/ycms.ocmod.xml) и проверить присутствие кода счетчика на страницах сайта.
