### ISSUE TITLE
Как обновлять модуль?

### ISSUE THREAD

**Issue by zipfo** [yandex-money/yandex-money-cms-opencart2#66]
При установке через стандартный установщик модулей, выдает "Модификация Y.CMS использует тот же идентификационный код". Была версия 1.02, отключил и удалил модификатор, после этого установил архив ycms.ocmod.zip, стала версия модификатора 1.04.
В модулях оплаты выдает версию Y.CMS от Яндекс.Кассы (1.4.1) и пишет "У вас неактуальная версия модуля. Вы можете загрузить и установить новую (1.5.0) ", пробовал вручную загрузить все файлы из архива, всё заменилось, но версия так и осталась 1.4.1

**Comment by neccospb** [comment]
модификаторы забыли обновить.

**Comment by zipfo** [comment]
Спасибо, не помогло. Так и осталось 1.4.1

**Comment by zipfo** [comment]
![2016-06-29_11-14-45](https://cloud.githubusercontent.com/assets/17256723/16445390/1f78d3d8-3deb-11e6-8983-84f834398b57.png)
![2016-06-29_11-15-49](https://cloud.githubusercontent.com/assets/17256723/16445392/1fa2f992-3deb-11e6-905e-c8131ba23505.png)

**Comment by neccospb** [comment]
попробуйте вручную залить с заменой файлы из архива, может там что-то с правами записи к файлам или почистить кэш вашего браузера (ctr+shift+del для хрома)

**Comment by zipfo** [comment]
Спасибо, оказалось что я сам себе злобный буратино, начал все файлы перебирать, выяснилось что когда-то при установке модуля не найдя папки russian в language, скопировал содержимое english в russian, и опенкарт тянула языковые файлы из russian, которые соответственно не менялись. Теперь еще такой вопрос, сверял содержимое папок, оказалось что в папке admin\model\yamodule есть файлы cryptor.php и mws.php, а в свежем архиве с модулем их нет. Они нужны?

**Comment by neccospb** [comment]
Были изменения в архитектуре, поэтому, возможно, теперь они не нужны.
