### ISSUE TITLE
Статус заказа всегда Новая покупка.

### ISSUE THREAD

**Issue by Aspirin8377** [yandex-money/yandex-money-cms-opencart2#67]
При прием платежей в кошелек на Яндекса статус у заказа почему-то всегда становится Новая покупка, даже если платеж в итоге не был сделан.  OpenCart 2.1.0.2

**Comment by neccospb** [comment]
Настройки модуля - Дополнительные настройки для администратора - Статус заказа после оплаты?

**Comment by Aspirin8377** [comment]
Менял там, но это никак не повлияло ни на что. Заказ сразу попадает в статус Новая покупка, в момент когда меня перебрасывает на Яндекс для оплаты. И оплатил я там или нет уже не влияет на статус заказа.

**Comment by ikarmanov** [comment]
Добрый день.

Хороший вопрос. Нужно разобраться. Вы сможете написать про Ваш случай на адрес cms@yamoney.ru
