### ISSUE TITLE
Ошибка в 2.2 ЯМаркет

### ISSUE THREAD

**Issue by sopranofirst** [yandex-money/yandex-money-cms-opencart2#68]
Устанавливаю чистую OPENCART 2.2, ставлю Ваш модуль через установщик, предварительно установив QuickFix+OC2.2.0.0. Обновляю модификатор, захожу в  feed настраиваю яндекс маркет, при генерации файла ошибка. 
Notice: Undefined index: code in /var/www/u021016/data/www/s.ru/catalog/controller/feed/yamarket.php on line 40Notice: Undefined index: value in /var/www/u021016/data/www/s.ru/catalog/controller/feed/yamarket.php on line 40Notice: Undefined index: code in /var/www/u021016/data/www/s.ru/catalog/controller/feed/yamarket.php on line 78Notice: Undefined index: code in

В чем проблема?

**Comment by ikarmanov** [comment]
Ошибка может быть связана с настройками валюты для Вашего магазина. Рекомендую проверить наличие валюты с кодом "RUB" и/или значения кол-ва знаков после запятой (рекомендую указать 2).
