### ISSUE TITLE
Ошибка при оплате QIWI wallet

### ISSUE THREAD

**Issue by Alexmsk11** [yandex-money/yandex-money-cms-opencart2#69]
При выборе способа оплаты QIWI wallet

выводиться сообщение 

Что-то пошло не так
Техническая ошибка

**Comment by ikarmanov** [comment]
Добрый день.

Это может быть связано с настройкой этого метода на нашей стороне. Рекомендую попросить менеджера Яндекс.Кассы проверить включение этого метода.
