### ISSUE TITLE
Не происходит перенаправления на сайт Яндекс.Деньги

### ISSUE THREAD

**Issue by vicgor** [yandex-money/yandex-money-cms-opencart2#7]
Не происходит перенаправления на сайт Яндекс.Деньги по ссылке
http://17i7.ru/index.php?route=payment/yamodule/yaredirect

**Comment by ded100let** [comment]
напиши мне в скайп d-link570

**Comment by vicgor** [comment]
необходима регистрация приложения для Яндекс.Деньги https://sp-money.yandex.ru/myservices/new.xml

Но логично выдавать сообщение об ошибке
