### ISSUE TITLE
Короткий <description> и <delivery-options>

### ISSUE THREAD

**Issue by skovorodka** [yandex-money/yandex-money-cms-opencart2#71]
Доброго времени суток!

Вопросы по Я.Маркет:
1. Почему такой короткий <description>, можно ли как-то увеличить длину описания?
   "На текст в элементе description действуют ограничения — длина не более 175 символов (не включая знаки препинания)"
2. Подскажите, когда планируется замена устаревшего <local_delivery_cost> на <delivery-options>?

Спасибо!

**Comment by ikarmanov** [comment]
Добрый день.

1. Из-за требований сервиса Яндекс.Маркет к параметру description.
2. Опишите Ваш вопрос подробнее.

**Comment by skovorodka** [comment]
Добрый!

1. Сейчас, после установки модуля вижу длину description до 100 знаков.

Яндекс пишет по этому поводу: "В элементе description указывается описание товарного предложения. В описании товарного предложения рекомендуется указывать основные характеристики товара. Элемент description может использоваться во всех типах описаний товарных предложений. На текст в элементе description действуют ограничения — длина не более 175 символов (не включая знаки препинания), запрещено использовать HTML-теги (в противном случае информация внутри тегов публиковаться не будет).
Если длина описания выходит за пределы допустимого значения, то при публикации текст обрезается и в конце ставится многоточие. "

Остается ещё 75 полезных символа + многоточие.

2. Имелось ввиду: замена local_delivery_cost на новый delivery-options.

Спасибо!

**Comment by AnnaNazarova** [comment]
Добрый день, столкнулась с проблемой! После выгрузки на маркет вместо нормального описания, которое есть на сайте выдает вот такое  <description>  Normal  0  false  false  false MicrosoftInternetExplorer4 </description>
C чем это связано? Где искать?

**Comment by densenator** [comment]
Вот тут https://yandex.ru/support/partnermarket/elements/description.xml
Указано, что Максимальная длина текста в элементе description — 3 000 символов (включая знаки препинания).
Можно в модуле как-то увеличить длину описания?

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо за информацию. Изменения документации проверили. Скоро доработаем.

**Comment by densenator** [comment]
Может быть заодно добавите "галочку" для выгрузки описания с тегами через <![CDATA[...]]> ?

**Comment by ikarmanov** [comment]
В новой версии модуля увеличили размер описания до 3000 символов
