### ISSUE TITLE
Заказ на Маркете не работает, если доставка в магазине не настроена на все регионы

### ISSUE THREAD

**Issue by denisyfrolov** [yandex-money/yandex-money-cms-opencart2#72]
Яндекс передает в заказе данные о регионе, стране и адресе доставки товара:

`{
   "cart":{
      "currency":"RUR",
      "items":[
         {
            "feedId":123,
            "offerId":"124",
            "feedCategoryId":"125",
            "offerName":"126",
            "count":1
         }
      ],
      "delivery":{
         "region":{
            "id":213,
            "name":"Москва",
            "type":"CITY",
            "parent":{
               "id":1,
               "name":"Москва и Московская область",
               "type":"SUBJECT_FEDERATION",
               "parent":{
                  "id":3,
                  "name":"Центральный федеральный округ",
                  "type":"COUNTRY_DISTRICT",
                  "parent":{
                     "id":225,
                     "name":"Россия",
                     "type":"COUNTRY"
                  }
               }
            }
         }
      }
   }
}`

Однако в методе index(), класса ControllerYandexbuyCart эти данные не учитываются. На строке 151 объявляется массив $address_array с пустыми значениями:

`$address_array = array(
                        'firstname'      => '',
                        'lastname'       => '',
                        'company'        => '',
                        'address_1'      => '',
                        'address_2'      => '',
                        'postcode'       => '',
                        'city'           => '',
                        'zone_id'        => '',
                        'zone'           => '',
                        'zone_code'      => '',
                        'country_id'     => '',
                        'country'        => '',
                        'iso_code_2'     => '',
                        'iso_code_3'     => '',
                        'address_format' => ''
                    );`

 Который в последующем используется для определения методов доставки, доступных товару, строка 198:

`$quote = $this->{'model_shipping_'.$result['code']}->getQuote($address_array);`

Если метод доставки не привязан ко всем регионам, то соответственно он не включается в доставку для выбранного товара и Яндексу возвращается пустой массив методов доставки:

`{
   "cart":{
      "items":[
         {
            "feedId":123,
            "offerId":"124",
            "price":375,
            "count":1,
            "delivery":true
         }
      ],
      "deliveryOptions":[],
      "paymentMethods":[
         "YANDEX",
         "CASH_ON_DELIVERY",
         "CARD_ON_DELIVERY"
      ]
   }
}`

Что приводит к ошибке INVALID_RESPONSE: INVALID_DATA со стороны парсера Яндекса. 

Кроме того, те идентификаторы, которые предает Яндекс магазину о регионе и стране доставки - не совпадают с данными в OpenCart2. Например, Россия для Яндекса - это регион с идентификатором 225, тогда как для OpenCart2, Россия значится под идентификатором 176. С городами и областями такая же история. Москва в Яндексе проходит под ID 213, тогда как в OpenCart эта зона имеет ID 83.

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо за подробное описание. Учтем Ваши замечания при выходе следующей версии модуля.
