### ISSUE TITLE
Некорректный ответ магазина на зпрос от Яндекса с неверным токеном

### ISSUE THREAD

**Issue by denisyfrolov** [yandex-money/yandex-money-cms-opencart2#73]
При передаче неверного токена Y.CMS отвечает статусом 404, тогда как Яндекс Маркет требует статус 403: https://tech.yandex.ru/market/partner/doc/dg/concepts/inform-on-errors-docpage/

Из-за этого магазин не может пройти проверку для "Заказа на Маркете".

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо. Учтем Ваши замечания при выходе следующей версии модуля.
