### ISSUE TITLE
Выгрузка не проходит модерацию в Маркете

### ISSUE THREAD

**Issue by kamar87** [yandex-money/yandex-money-cms-opencart2#77]
В описании товаров есть переход на новую строку, при формировании YML в поле description этот переход заменяется на &#13; модераторы ругаются на данные коды.

**Comment by kamar87** [comment]
`"&#13;"`

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо за информацию. Мы проверим этот факт и внесем необходимые изменения в следующих версиях модуля.

**Comment by ikarmanov** [comment]
Рекомендуем исключить из описания перенос строки с символом &#13;
