### ISSUE TITLE
В заказе не учитывается стоимость доставки

### ISSUE THREAD

**Issue by denisyfrolov** [yandex-money/yandex-money-cms-opencart2#78]
В классе ControllerYandexbuyOrder, в методе accept() не устанавливаются данные доставки, хотя Маркет их передает в запросе. Из-за чего магазин не учитывает стоимость доставки и ее приходится устанавливать вручную уже после формирования заказа.

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо за информацию. Мы проверим этот факт и внесем необходимые изменения в следующих версиях модуля.

**Comment by ikarmanov** [comment]
Рекомендуем обновить модуль до 2.1.0 (просто установить новую версию). Сообщите результат
