### ISSUE TITLE
Замените <footer> на <footer в ycms.ocmod.xml для улучшения совместимости с шаблонами

### ISSUE THREAD

**Issue by turistpro** [yandex-money/yandex-money-cms-opencart2#79]
<file path="catalog/view/theme/*/template/common/footer.tpl">
		<operation>
			<search><![CDATA[<footer]]></search>
			<add position="Before" ofset="1"><![CDATA[
...

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо за информацию. Мы проверим этот факт и внесем необходимые изменения в следующих версиях модуля.
