### ISSUE TITLE
Не работает Яндекс.Метрика

### ISSUE THREAD

**Issue by vicgor** [yandex-money/yandex-money-cms-opencart2#8]
Не работает Яндекс.Метрика

После настроек на вкладке Яндекс.Метрика данные статистики не отображается 
Сервис Яндекс.Метрики https://metrika.yandex.by/list/ сообщает что код счетчика не найден, но данные поступают

**Comment by ded100let** [comment]
я написал что сделать в скайп добавь меня. ты чтото не так сделал).

**Comment by vicgor** [comment]
необходим vqmod, с vqmod работает
Но хорошо бы добавить описание настройки метрики
