### ISSUE TITLE
Не выводит цены в прайс :(

### ISSUE THREAD

**Issue by AnatolySt** [yandex-money/yandex-money-cms-opencart2#82]
Здравствуйте! Сначала не выводились товары вообще, нашел фикс, поменял true на false в файле yamarket.php:

`$products = $this->model_yamodel_yamarket->getProducts($ids_cat, false);`

Товары выводятся, но без цены. Скриншот:
[https://pp.vk.me/c636224/v636224302/19dee/y5ApOcvL0Wk.jpg]

Заранее благодарю. Надеюсь на скорый ответ

**Comment by ikarmanov** [comment]
Добрый день.

Проблемы с отображением цены могут быть вызваны отсутствием настроек валюты Рубль (RUB). Рекомендую проверить значение параметра "Кол-во знаков после запятой" в настройках валюты.
