### ISSUE TITLE
Как редактировать тег sales_notes?

### ISSUE THREAD

**Issue by zolototv** [yandex-money/yandex-money-cms-opencart2#83]
Магазин не проходит модерацию. Требуют указать 100% предоплату в YML

> Пожалуйста, укажите в прайс-листе в теге sales_notes информацию о предоплате.

В вашем модуле не могу найти такую настройку.

ocStore 2.1.0.2
 Y.CMS от Яндекс.Кассы (версия 1.5.0)

Спасибо.

**Comment by ikarmanov** [comment]
Добрый день.

Такой настройки сейчас нет, но она есть в планах на добавление в новую версию модуля. Вы можете самостоятельно добавить под [строку 86](https://github.com/yandex-money/yandex-money-cms-opencart2/blob/dcb8aa9089a28f41b5c62e475fddb65e1991bef6/src/upload/catalog/controller/feed/yamarket.php#L86) значение `$data['sales_notes'] = 'ваш_текст';`.

**Comment by zolototv** [comment]
Извините, а не подскажите где находится файл YML?
И сохранятся ли изменения, ведь файл периодически обновляется модулем?

**Comment by ikarmanov** [comment]
Добрый день.

Файл YML генерируется динамически. Если у вас есть дополнительные вопросы по работе модуля, то рекомендую направлять их на cms@yamoney.ru

**Comment by iamnovocaine** [comment]
Здравствуйте, сделала изменения в файле согласно вышеуказанным рекомендациям, изменений в файле YML не видно. Что нужно сделать? писала на cms@yamoney.ru, не отвечаете

**Comment by ikarmanov** [comment]
Добрый день.

Укажите кусок кода (+/- 5 строк) с вашими правками. Я проверю.

**Comment by iamnovocaine** [comment]
Добрый день.

```
//.....

if($product['quantity'] < 1){
    $stock_id = $product['stock_status_id'];
    $delivery_cost = $this->config->get('ya_market_stock_cost');
    $delivery_days = $this->config->get('ya_market_stock_days');
    $data['delivery-options'][] = array(
          'cost' => $delivery_cost[$stock_id],
          'days' => $delivery_days[$stock_id]
     );
 }
if ($product['minimum'] > 1)
  $data['sales_notes'] = 'Минимальное кол-во для заказа: '.$product['minimum'];
if ($this->config->get('config_comment')) {
  $data['sales_notes'] = 'Необходима предоплата 100%';
  //$data['sales_notes'] = $this->config->get('config_comment');
}
$data['picture'] = array();
if (isset($product['image'])) $data['picture'][] = str_replace(" ", "%20", $this->model_tool_image->resize($product['image'], 600, 600));
foreach ($this->model_catalog_product->getProductImages($data['id']) as $pic){
   if (count($data['picture'])<=9) $data['picture'][] = str_replace(array('&amp;',' '),array('&', '%20'), $this->model_tool_image->resize($pic['image'], 600, 600));
}
//......
```
Спасибо

**Comment by ikarmanov** [comment]
Рекомендуем не вносить правки, а оставить так
```
if ($this->config->get('config_comment')) {
  $data['sales_notes'] = $this->config->get('config_comment');
}
```
Сам текст для sales_nores можно установить в [настройках магазина](https://yadi.sk/i/crM8I-Rr3J53rB).
