### ISSUE TITLE
 Установите дополнение Яндекс.Деньги на вкладке модулей оплаты. 

### ISSUE THREAD

**Issue by aldonintra** [yandex-money/yandex-money-cms-opencart2#84]
Установил Y.CMS от Яндекс.Кассы (1.5.1)
Версия Opencart Version 2.3.0.2 (trs-2.3.0.0)
Включил Библиотека для Y.CMS OpenCart2 в пункте Оплата
При переходе в каналах продаж пишет Установите дополнение Яндекс.Деньги на вкладке модулей оплаты. В чем может быть проблема?

**Comment by ikarmanov** [comment]
Добрый день.

Для CMS Opencart 2.3.x нами разработан универсальный модуль, который можно [загрузить здесь](https://github.com/yandex-money/yandex-money-cms-opencart2/tree/oc23x).
