### ISSUE TITLE
Если в поле описания товара есть символ &, то формируется некорректный xml

### ISSUE THREAD

**Issue by litvinov-online** [yandex-money/yandex-money-cms-opencart2#85]

**Comment by noobsaibot88** [comment]
Название или описание. Таких товаров полно, например soler & palau. С таким багом решение неработоспособно.

**Comment by HugeTool** [comment]
используйте `&amp;`

**Comment by ikarmanov** [comment]
**HugeTool**, спасибо и Вы правы.
