### ISSUE TITLE
Могу ли я установить модуль Y.CMS на Opencart версии 2.3.0.2 ?

### ISSUE THREAD

**Issue by Chelovekmolekula** [yandex-money/yandex-money-cms-opencart2#86]
Могу ли я установить модуль Y.CMS на Opencart версии 2.3.0.2 ?

**Comment by ikarmanov** [comment]
Добрый день.

Да. Загрузить его можно [тут](https://github.com/yandex-money/yandex-money-cms-opencart2/tree/oc23x)

**Comment by denvlkab** [comment]
я установил его, но почему то ругается, что нет прав http://joxi.ru/12MWGpDCMwKnNr
http://joxi.ru/gmv8J7qFLdM89A
Хотя я являюсь единственным пользователем ... 
и в правах админа, сделал все галочки ... 
Устанавливал модуль до регистрации и договора с ЯДом ... сейчас есть договор и все дела, но
ПОМОГИТЕ .
или как его можно удалить?
