### ISSUE TITLE
Ошибка при открытии YML

### ISSUE THREAD

**Issue by shelomitsky2011** [yandex-money/yandex-money-cms-opencart2#87]
Отметил категории. Открываю этот файл и оказывается в нём ошибка.
Notice: Undefined index: value in /var/www/u0199323/public_html/catalog/controller/feed/yamarket.php on line 37
Что с этим можно сделать?
И да, как seowizard попытался прочитать этот файл, вместо названий категорий кракозябры всякие

**Comment by ikarmanov** [comment]
Добрый день.

Рекомендую установить актуальную версию модуля ([1.6.0](https://github.com/yandex-money/yandex-money-cms-opencart2) для Opencart 2.0.x-2.2.x, [2.0.0](https://github.com/yandex-money/yandex-money-cms-opencart2/tree/oc23x) для Opencart 2.3.x) и посмотреть на результат.
