### ISSUE TITLE
Ошибка 51

### ISSUE THREAD

**Issue by Zanimo** [yandex-money/yandex-money-cms-opencart2#88]
Здравствуйте, не получается воспользоваться модулем из-за повторяющейся ошибки:
Размещение Вашего магазина site.ru было приостановлено за повторяющиеся ошибки в прайс-листе. Не удалось получить файл :
server status is no status code; ERR: errcode: 51, msg: SSL: no alternative certificate subject name matches target host name 'site.ru'; 
Для себя отметил, что одновременно становится недоступной и я.метрика. Прописал код на сайте - метрика, разумеется, работает без проблем!
Установлена была последняя версия модуля, но почему-то файл OCMOD имел номер старой версии, так и есть? Использовал под ocStore 2.1.0.2.1
В чем может быть проблема?

**Comment by ikarmanov** [comment]
Добрый день.

Ошибка из Вашего сообщения указывает на проблему с SSL-сертификатом.
