### ISSUE TITLE
Как клиенту оплатить заказ если не смог этого сделать на этапе оформления заказа?

### ISSUE THREAD

**Issue by zipfo** [yandex-money/yandex-money-cms-opencart2#89]
Ситуация, клиент оформляет заказ, он создается в системе со статусом "принят, ожидается оплата", клиент автоматически переадресуется на страницу оплаты в кассе, выбор способа оплаты происходит на стороне кассы, клиент выбирает способ оплаты вводит данные но оплата не проходит (что-то пошло не так), если клиент был авторизован на яндексе в кабинете кассы платеж создается неоплаченным с его номером кошелька на я.деньги вне зависимости от того какой способ он выбирал, корзина на сайте чистится, клиент заходит на сайт снова, как ему оплатить уже созданный не оплаченный заказ?

**Comment by iMateo** [comment]
Получите от него адрес почты (если еще нет) и можно выставить ему счет на почту. Там будет кнопка оплатить, сумму вы указываете при формировании счета (в кассе).

**Comment by zipfo** [comment]
![2016-08-25_09-55-24](https://cloud.githubusercontent.com/assets/17256723/17959619/29bee2d8-6aaa-11e6-88c8-6d63eabbb54a.png)
Вы про это? Если да то при оформлении заказа приходит письмо вида:
Благодарим за интерес к товарам %shop_name%. Ваш заказ получен и поступил в обработку.
Для просмотра Вашего заказа перейдите по ссылке:
http://%shop_url%/index.php?route=account/order/info&order_id=55

и дальше детали заказа, платежный адрес, список заказанных товаров, кнопки оплатить там нет

**Comment by zipfo** [comment]
Нашел где выставлять счет вручную: заказы, оранжевая кнопка с конвертом (выставление счета)

**Comment by Alexmsk11** [comment]
Как сделать чтобы письмо/счет с кнопкой для оплаты, отправлялось автоматически ?

из 10 клиентов - 9 (по различным причинам) не могут оплатить сразу. 
Каждому приходиться высылать счет на оплату в ручную - очень не удобно. 
Хотелось бы автоматизировать этот процесс.

**Comment by webair-studio** [comment]
О, я не один такой, оказывается. Тоже зашел написать про то, что нельзя вернуться к оплате, если случайно закрыл вкладку или что то пошло не так в процессе оплаты. Частенько пишут покупатели с такой проблемой.
Как можно сделать, чтобы вместе с письмом приходила постоянная ссылка на оплату?

**Comment by webair-studio** [comment]
Вариант - сделать автоматическое выставление счета на email с помощью https://money.yandex.ru/bill/?from=iget&_openstat=iget%3Bbill и обрабатывать результат платежа с помощью http уведомлений

**Comment by ikarmanov** [comment]
Добрый день.

Функция выставления счета на электронный адрес плательщика реализован для сервиса Яндекс.Касса. Разработку похожего функционала для режима "пополнения кошелька" Яндекс.Денег  мы рассмотрим. Сроки рассмотрения сказать затрудняюсь.

**Comment by Alexmsk11** [comment]
Как сделать чтобы письмо/счет с кнопкой для оплаты, отправлялось не в ручном режиме, а автоматически (для Яндекс.Касса)?

**Comment by yuranikspb** [comment]
Почему у сторонних разработчиков реализовано отложенная оплата а у вас нет ?, 
сделайте уже в конце концов оплату из истории заказов, Ну закрыл человек скажем страницу оплаты , а потом хочет оплатить как ему это сделать ? первым делом лезут в личный кабинет и ищут кнопку оплаты а ее нет!

**Comment by ikarmanov** [comment]
Добрый день.

Спасибо за обратную связь. Готовим обновление модуля по feedback'у из Github. Отложенную оплату будем добавлять позже (точных сроков нет), а вот с переходом к оплате из истории уже проверяем.

**Comment by ikarmanov** [comment]
Реализовано в новой версии модуля (2.1.0)
