### ISSUE TITLE
Нет возможности редактирования 

### ISSUE THREAD

**Issue by Keksoidik** [yandex-money/yandex-money-cms-opencart2#90]
"Авторизационный токен" - Данная строка заблокирована от записи
Получить токен для доступа к программе "Заказы на маркете"

Вверху имеется ошибка.
Warning: explode() expects parameter 2 to be string, array given in /home/e-smith/files/ibays/styleok/html/admin/controller/feed/yamodule.php on line 599

**Comment by ikarmanov** [comment]
Добрый день.

Какая версия модуля и Opencart у вас установлена?
