### ISSUE TITLE
Ошибка кнопки "Управление заказом"

### ISSUE THREAD

**Issue by webair-studio** [yandex-money/yandex-money-cms-opencart2#91]
![2016-09-01_144451](https://cloud.githubusercontent.com/assets/18102692/18166242/aefdcac4-7052-11e6-9255-6664b6db9362.jpg)
Для чего предназначена эта кнопка? При ее нажатии начинается бесконечная загрузка страницы и всё же потом вываливается ошибка:
`Fatal error: Uncaught exception 'Exception' with message 'Error: MySQL server has gone away<br />Error No: 2006<br />SELECT * FROM`oc_mws_return`o WHERE o.invoice_id = '0' ORDER BY`date`DESC' in /home/w/webair/otkrytky/public_html/system/library/db/mysqli.php:40 Stack trace: #0 /home/w/webair/otkrytky/public_html/system/library/db.php(16): DB\MySQLi->query('SELECT * FROM`...', Array) #1 /home/w/webair/otkrytky/public_html/admin/model/yamodule/return.php(9): DB->query('SELECT \* FROM `...') #2 [internal function]: ModelYamoduleReturn->getSuccessReturns(0) #3 /home/w/webair/otkrytky/public_html/system/storage/modification/system/engine/loader.php(188): call_user_func_array(Array, Array) #4 [internal function]: Loader->{closure}(Array) #5 /home/w/webair/otkrytky/public_html/system/engine/proxy.php(13): call_user_func(Object(Closure), Array) #6 /home/w/webair/otkrytky/public_html/admin/controller/yamodule/mws.php(179): Proxy->__call('getSuccessRetur...', Array) #7 /home/w/webair/otkrytky/public_html/admin/controller/yamod in /home/w/webair/otkrytky/public_html/system/library/db/mysqli.php on line 40`
opencart 2.2, php 5.6

**Comment by ikarmanov** [comment]
Добрый день.

Модуль `Y.CMS от Яндекс.Кассы` в Каналах продвижения установлен? Если было обновление с других версий модуля, то рекомендую переустановить наш модуль (Отключить/Включить).
Кнопка необходима для выполнения возврата по платежам через Яндекс.Кассу.

**Comment by webair-studio** [comment]
У меня используется P2P Яндекс Деньги в Y.CMS.
Было бы логично тогда убирать эту кнопку, если Яндекс Касса выключена. Я уберу вручную :)

**Comment by lyolic** [comment]
Использую Яндекс деньги(не кассу).
Если в каналах продвижения модульне включен, то 
При нажатии на эту кнопку вываливаются сообщения:
<b>Notice</b>: Undefined index: ya_kassa_test in <b>/var/www/html/admin/controller/tool/mws.php</b> on line <b>134</b>
<b>Notice</b>: Undefined index: ya_kassa_sid in <b>/var/www/html/admin/controller/tool/mws.php</b> on line <b>135</b>


если включен, то имеем:
 Управление денежными средствами
В модуле Яндекс.Касса указан пустой идентификатор магазина (shopId)
Модуль Яндекс.Кассы отключен
Проблема с сертификатом, отсутствием оплаты по данному заказу или указан ошибочный идентификатор магазина

**Comment by ikarmanov** [comment]
Спасибо за информацию. Скоро поправим

**Comment by ikarmanov** [comment]
Кнопка скрыта в новой версии модуля.
