### ISSUE TITLE
Ошибка "Error total amount"

### ISSUE THREAD

**Issue by Mekhet** [yandex-money/yandex-money-cms-opencart2#94]
Здравствуйте! Могли бы вы подсказать в чем может быть проблема. Мы установили модуль Y.CMS OpenCart2 .. и при оплате возникает ошибка "Что-то пошло не так" .. в службе поддержки яндекса написали что идет ответ:

<?xml version="1.0" encoding="UTF-8"?>
                         <check Order Response performed Date time="2016-10-04T18:38:11+03:00" code="100" invoiceId="2000000923192" techMessage="Error total amount" shopId="75856"/>
Проблема где-то на стороне вашего сайта.

Ошибка "Ошибка общая сумма"
Но в чем конкретно заключается проблема непонятно. У вас уже возникали подобные случаи в работе модуля? Можете подсказать где копать?

**Comment by Mekhet** [comment]
Попробовали переустановить полностью модуль.. теперь при выборе оплаты Яндекс кнопка перейти к оплате вообще перестала работать..  в чем беда?

**Comment by ikarmanov** [comment]
Добрый день.

Рекомендую написать на cms@yamoney.ru, если Ваш вопрос актуален.
