### ISSUE TITLE
Яндекс.Маркет

### ISSUE THREAD

**Issue by miken912** [yandex-money/yandex-money-cms-opencart2#95]
В версии 1.6 что то сломали, и вместо YML для яндекс маркет по адресу index.php?route=feed/yamarket выдается ошибка 500

**Comment by bolahg** [comment]
Блин обновился до 1.6 и все теперь не работает

**Comment by ikarmanov** [comment]
Добрый день.

Рекомендую написать на cms@yamoney.ru, если Ваш вопрос актуален.
