### ISSUE TITLE
Заказ на Маркете - не работает

### ISSUE THREAD

**Issue by xxBRATxx** [yandex-money/yandex-money-cms-opencart2#96]
установил данный модуль, получил сертификат ssl, все настроено с рекомендацией маркета и учетом требования модуля. из модуля получаю oauth токен, выполняю тестовые заказы из партнерского интерфейса, получаю и ошибки 3XX, 11XX
тоже самое с метрикой.

**Comment by ikarmanov** [comment]
Добрый день.

Рекомендую написать на cms@yamoney.ru, если Ваш вопрос актуален.
