### ISSUE TITLE
не полный путь картинок в XML формируемом для Маркета

### ISSUE THREAD

**Issue by Alexmsk11** [yandex-money/yandex-money-cms-opencart2#98]
OpenCart 2.2.0.0
Y.CMS от Яндекс.Кассы (1.5.1)

Модуль формирует XML file по адресу https://адрес-сайта/shop/index.php?route=feed/yamarket

Товары загружаются на Маркет БЕЗ картинок

при изучении XML file видим, что путь к картинкам имеет вид:

`<picture>image/cache/catalog/1netprint-600x600.jpg</picture>`

БЕЗ указания адреса сайта, очевидно для того чтобы картинки отображались нужно добавить в начале адрес сайта

`<picture>https://адрес-сайта/shop/cache/catalog/1netprint-600x600.jpg</picture>`

Вопрос как это сделать?

**Comment by Alexmsk11** [comment]
кто нибудь живой есть из поддержки?

**Comment by ikarmanov** [comment]
Добрый день.

Рекомендую обратиться на cms@yamoney.ru, если Ваш вопрос актуален.
