### ISSUE TITLE
Не работает модуль

### ISSUE THREAD

**Issue by Rahashan** [yandex-money/yandex-money-cms-opencart2#99]
Магазин на Opencart 2.1.0.2. Скачал и установил модуль, прописал настройки магазина:
http://joxi.ru/lbrRZD5HEy4yr1

При попытке совершить тестовую оплату через Яндекс Кассу с выбором способа оплаты на стороне Яндекс Кассы получаю такой ответ после нажатия кнопки "Заплатить через Яндекс":
http://joxi.ru/el2ZkvRIQDa0AJ

При этом оплата проходит - пробовал оплатить товар 1 руб. банковской картой, но переадресация обратно на магазин не происходит, пишет "Что-то пошло не так".

**Comment by aderonix** [comment]
Была аналогичная проблема, решена была по телефону на стороне Я.Кассы.
Меня попросили обновить браузер до актуальной версии (проблема была в Google Chrome).
